<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('contact_segments',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->text('description')->nullable();$t->json('conditions');$t->unsignedInteger('cached_count')->default(0);$t->boolean('active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('contact_lists',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->text('description')->nullable();$t->boolean('active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('contact_list_members',function(Blueprint $t):void{$t->foreignId('contact_list_id')->constrained()->cascadeOnDelete();$t->foreignId('contact_id')->constrained()->cascadeOnDelete();$t->foreignId('added_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('created_at')->useCurrent();$t->primary(['contact_list_id','contact_id']);});
 Schema::create('support_forms',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->boolean('active')->default(true);$t->json('settings')->nullable();$t->foreignId('default_team_id')->nullable()->constrained('teams')->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('support_form_fields',function(Blueprint $t):void{$t->id();$t->foreignId('support_form_id')->constrained()->cascadeOnDelete();$t->string('key');$t->string('label');$t->string('type',24);$t->boolean('required')->default(false);$t->json('options')->nullable();$t->unsignedInteger('display_order')->default(0);$t->unique(['support_form_id','key']);});
 Schema::create('support_form_submissions',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('support_form_id')->constrained()->cascadeOnDelete();$t->foreignId('contact_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('ticket_id')->nullable()->constrained()->nullOnDelete();$t->json('payload');$t->string('status',24)->default('received');$t->string('ip_hash',64)->nullable();$t->timestamp('submitted_at')->useCurrent();$t->timestamps();});
 Schema::create('help_center_settings',function(Blueprint $t):void{$t->id();$t->string('name')->default('Help Center');$t->string('slug')->default('help')->unique();$t->text('welcome_text')->nullable();$t->string('primary_color',16)->default('#2563eb');$t->boolean('active')->default(false);$t->boolean('allow_ticket_submission')->default(true);$t->boolean('allow_portal')->default(true);$t->json('seo')->nullable();$t->timestamps();});
 Schema::create('customer_portal_tokens',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('contact_id')->constrained()->cascadeOnDelete();$t->string('token_hash',64)->unique();$t->timestamp('expires_at');$t->timestamp('last_used_at')->nullable();$t->timestamp('revoked_at')->nullable();$t->timestamps();});
 Schema::create('csat_surveys',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('question');$t->string('resource_type',32)->default('conversation');$t->unsignedTinyInteger('scale')->default(5);$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('csat_responses',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('csat_survey_id')->constrained()->cascadeOnDelete();$t->string('resource_type',32);$t->unsignedBigInteger('resource_id');$t->foreignId('contact_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('rating');$t->text('comment')->nullable();$t->string('response_token_hash',64)->unique();$t->timestamp('submitted_at')->useCurrent();$t->timestamps();$t->index(['resource_type','resource_id']);});
 Schema::create('saved_reports',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('report_type',32);$t->json('filters')->nullable();$t->json('columns')->nullable();$t->string('schedule',32)->nullable();$t->json('recipients')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('developer_api_keys',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('token_prefix',16);$t->string('token_hash',64)->unique();$t->json('scopes');$t->timestamp('last_used_at')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamp('revoked_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('api_request_logs',function(Blueprint $t):void{$t->id();$t->foreignId('developer_api_key_id')->nullable()->constrained()->nullOnDelete();$t->string('method',8);$t->string('path',512);$t->unsignedSmallInteger('status_code');$t->unsignedInteger('duration_ms');$t->string('ip_hash',64)->nullable();$t->timestamp('created_at')->useCurrent()->index();});
 Schema::create('outbound_webhooks',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('url',2048);$t->json('events');$t->text('secret_encrypted');$t->boolean('active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('outbound_webhook_deliveries',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('outbound_webhook_id')->constrained()->cascadeOnDelete();$t->string('event',100);$t->string('event_id',64)->unique();$t->json('payload');$t->unsignedSmallInteger('attempts')->default(0);$t->string('status',24)->default('pending')->index();$t->unsignedSmallInteger('response_code')->nullable();$t->text('response_excerpt')->nullable();$t->timestamp('next_attempt_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamps();});
 Schema::create('data_retention_policies',function(Blueprint $t):void{$t->id();$t->string('resource_type',64)->unique();$t->unsignedInteger('retain_days');$t->boolean('active')->default(false);$t->string('action',24)->default('anonymize');$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('privacy_requests',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('contact_id')->constrained()->cascadeOnDelete();$t->string('type',24);$t->string('status',24)->default('pending');$t->timestamp('requested_at')->useCurrent();$t->timestamp('completed_at')->nullable();$t->text('notes')->nullable();$t->foreignId('handled_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 }public function down():void{foreach(['privacy_requests','data_retention_policies','outbound_webhook_deliveries','outbound_webhooks','api_request_logs','developer_api_keys','saved_reports','csat_responses','csat_surveys','customer_portal_tokens','help_center_settings','support_form_submissions','support_form_fields','support_forms','contact_list_members','contact_lists','contact_segments'] as $table)Schema::dropIfExists($table);}};
