<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::create('qa_scorecards',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->json('criteria');$t->unsignedInteger('passing_score')->default(80);$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('qa_reviews',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('qa_scorecard_id')->constrained()->cascadeOnDelete();$t->string('resource_type',32);$t->unsignedBigInteger('resource_id');$t->foreignId('agent_id')->constrained('users')->cascadeOnDelete();$t->foreignId('reviewer_id')->constrained('users')->cascadeOnDelete();$t->json('scores');$t->unsignedInteger('total_score');$t->text('feedback')->nullable();$t->string('status',24)->default('completed');$t->timestamp('reviewed_at')->useCurrent();$t->timestamps();});
 Schema::create('coaching_sessions',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('agent_id')->constrained('users')->cascadeOnDelete();$t->foreignId('coach_id')->constrained('users')->cascadeOnDelete();$t->foreignId('qa_review_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->text('notes')->nullable();$t->json('action_items')->nullable();$t->timestamp('scheduled_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
 Schema::create('workforce_shifts',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamp('starts_at');$t->timestamp('ends_at');$t->string('timezone',64);$t->string('status',24)->default('scheduled');$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['user_id','starts_at']);});
 Schema::create('time_off_requests',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->date('starts_on');$t->date('ends_on');$t->string('type',32);$t->string('status',24)->default('pending');$t->text('reason')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamps();});
 }public function down():void{foreach(['time_off_requests','workforce_shifts','coaching_sessions','qa_reviews','qa_scorecards'] as $table)Schema::dropIfExists($table);}};
