<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
 Schema::create('support_queues',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->text('description')->nullable();$t->foreignId('team_id')->nullable()->constrained()->nullOnDelete();$t->unsignedInteger('priority')->default(100);$t->boolean('active')->default(true);$t->string('assignment_method',32)->default('manual');$t->unsignedInteger('capacity')->nullable();$t->json('channel_scope')->nullable();$t->json('conditions')->nullable();$t->foreignId('last_assigned_user_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['active','priority']);});
 Schema::create('agent_presence',function(Blueprint $t):void{$t->foreignId('user_id')->primary()->constrained()->cascadeOnDelete();$t->string('status',16)->default('offline')->index();$t->unsignedInteger('conversation_capacity')->default(10);$t->unsignedInteger('ticket_capacity')->default(20);$t->timestamp('last_seen_at')->nullable();$t->timestamp('status_changed_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
 Schema::create('assignment_rules',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('resource_type',32);$t->unsignedInteger('priority')->default(100);$t->boolean('active')->default(true);$t->json('conditions');$t->json('actions');$t->boolean('stop_processing')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['resource_type','active','priority']);});
 Schema::create('sla_policies',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->text('description')->nullable();$t->boolean('active')->default(true);$t->unsignedInteger('priority')->default(100);$t->string('calendar_mode',16)->default('business_hours');$t->foreignId('business_hours_policy_id')->nullable()->constrained('business_hour_policies')->nullOnDelete();$t->json('targets');$t->json('pause_statuses')->nullable();$t->unsignedTinyInteger('approaching_percentage')->default(80);$t->json('conditions')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['active','priority']);});
 Schema::create('sla_instances',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('sla_policy_id')->constrained()->cascadeOnDelete();$t->string('resource_type',32);$t->unsignedBigInteger('resource_id');$t->string('priority',16);$t->string('state',24)->default('healthy')->index();$t->timestamp('started_at');$t->timestamp('first_response_due_at')->nullable()->index();$t->timestamp('next_response_due_at')->nullable()->index();$t->timestamp('resolution_due_at')->nullable()->index();$t->timestamp('first_response_fulfilled_at')->nullable();$t->timestamp('resolution_fulfilled_at')->nullable();$t->timestamp('paused_at')->nullable();$t->unsignedBigInteger('paused_seconds')->default(0);$t->timestamp('breached_at')->nullable();$t->timestamps();$t->unique(['resource_type','resource_id']);});
 Schema::create('escalation_policies',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->boolean('active')->default(true);$t->unsignedInteger('priority')->default(100);$t->json('conditions');$t->json('actions');$t->unsignedInteger('cooldown_minutes')->default(60);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['active','priority']);});
 Schema::create('escalation_executions',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('escalation_policy_id')->constrained()->cascadeOnDelete();$t->string('resource_type',32);$t->unsignedBigInteger('resource_id');$t->string('status',24)->index();$t->json('actions_executed')->nullable();$t->text('error_message')->nullable();$t->timestamp('executed_at')->useCurrent()->index();$t->timestamps();$t->index(['resource_type','resource_id','executed_at'],'escalation_resource_executed_idx');});
 } public function down():void{Schema::dropIfExists('escalation_executions');Schema::dropIfExists('escalation_policies');Schema::dropIfExists('sla_instances');Schema::dropIfExists('sla_policies');Schema::dropIfExists('assignment_rules');Schema::dropIfExists('agent_presence');Schema::dropIfExists('support_queues');} };
