<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('ticket_sequences',function(Blueprint $t):void{$t->string('key')->primary();$t->unsignedBigInteger('current_value')->default(0);$t->timestamps();});
  Schema::create('ticket_statuses',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('slug')->unique();$t->string('category',32)->index();$t->string('color',16)->default('#64748b');$t->unsignedInteger('display_order')->default(0);$t->boolean('is_default')->default(false);$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('ticket_categories',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('name');$t->string('slug');$t->foreignId('parent_id')->nullable()->constrained('ticket_categories')->nullOnDelete();$t->text('description')->nullable();$t->boolean('active')->default(true);$t->unsignedInteger('display_order')->default(0);$t->timestamps();$t->unique(['parent_id','slug']);$t->index(['active','display_order']);});
  Schema::create('tickets',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('ticket_number')->unique();$t->string('subject');$t->longText('description')->nullable();$t->foreignId('contact_id')->constrained()->restrictOnDelete();$t->foreignId('company_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('conversation_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('channel_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('team_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('assignee_id')->nullable()->constrained('users')->nullOnDelete();$t->string('priority',16)->default('normal')->index();$t->foreignId('status_id')->constrained('ticket_statuses')->restrictOnDelete();$t->foreignId('category_id')->nullable()->constrained('ticket_categories')->nullOnDelete();$t->string('source',32)->default('manual')->index();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('first_response_at')->nullable();$t->timestamp('resolution_due_at')->nullable()->index();$t->timestamp('resolved_at')->nullable();$t->timestamp('closed_at')->nullable();$t->unsignedBigInteger('sla_policy_id')->nullable()->index();$t->unsignedBigInteger('merged_into_id')->nullable()->index();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();$t->index(['status_id','assignee_id','updated_at']);$t->index(['team_id','status_id','updated_at']);});
  Schema::create('ticket_comments',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('ticket_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('author_name')->nullable();$t->text('body');$t->boolean('internal')->default(true);$t->timestamps();$t->index(['ticket_id','created_at']);});
  Schema::create('ticket_activities',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('ticket_id')->constrained()->cascadeOnDelete();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('actor_name')->nullable();$t->string('event_type',64)->index();$t->string('description');$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->json('metadata')->nullable();$t->timestamp('occurred_at')->useCurrent()->index();$t->timestamps();$t->index(['ticket_id','occurred_at']);});
  Schema::create('ticket_merges',function(Blueprint $t):void{$t->id();$t->foreignId('source_ticket_id')->constrained('tickets')->restrictOnDelete();$t->foreignId('destination_ticket_id')->constrained('tickets')->restrictOnDelete();$t->foreignId('merged_by')->nullable()->constrained('users')->nullOnDelete();$t->text('reason')->nullable();$t->timestamp('created_at')->useCurrent();$t->unique('source_ticket_id');});
  Schema::create('tasks',function(Blueprint $t):void{$t->id();$t->uuid('public_uuid')->unique();$t->string('title');$t->text('description')->nullable();$t->string('status',32)->default('todo')->index();$t->string('priority',16)->default('normal')->index();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('due_at')->nullable()->index();$t->timestamp('completed_at')->nullable();$t->string('related_type',32)->nullable();$t->unsignedBigInteger('related_id')->nullable();$t->foreignId('parent_task_id')->nullable()->constrained('tasks')->cascadeOnDelete();$t->timestamps();$t->softDeletes();$t->index(['assigned_to','status','due_at']);$t->index(['related_type','related_id']);});
 }
 public function down():void {Schema::dropIfExists('tasks');Schema::dropIfExists('ticket_merges');Schema::dropIfExists('ticket_activities');Schema::dropIfExists('ticket_comments');Schema::dropIfExists('tickets');Schema::dropIfExists('ticket_categories');Schema::dropIfExists('ticket_statuses');Schema::dropIfExists('ticket_sequences');}
};
