<?php
namespace App\Http\Controllers\Tenant\Admin\Reporting;
use App\Http\Controllers\Controller;use App\Models\Inbox\Conversation;use App\Models\Ticket\Ticket;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Symfony\Component\HttpFoundation\StreamedResponse;use Inertia\Inertia;use Inertia\Response;
class ReportingController extends Controller
{
 private function access(Request $r):void{abort_unless($r->user('tenant')->can('reports.view'),403);}private function range(Request $r):array{$d=$r->validate(['from'=>['nullable','date'],'to'=>['nullable','date','after_or_equal:from']]);return[$d['from']??now()->subDays(30)->startOfDay(),$d['to']??now()->endOfDay()];}
 public function index(Request $r):Response{$this->access($r);[$from,$to]=$this->range($r);$conversations=Conversation::whereBetween('created_at',[$from,$to]);$tickets=Ticket::whereBetween('created_at',[$from,$to]);return Inertia::render('Tenant/Admin/Reporting/Index',['filters'=>['from'=>(string)$from,'to'=>(string)$to],'metrics'=>['conversations'=>(clone $conversations)->count(),'tickets'=>(clone $tickets)->count(),'resolved_conversations'=>(clone $conversations)->whereIn('status',['resolved','closed'])->count(),'resolved_tickets'=>(clone $tickets)->whereHas('status',fn($q)=>$q->whereIn('category',['resolved','closed']))->count(),'first_response_minutes'=>(float)(Conversation::whereBetween('created_at',[$from,$to])->whereNotNull('first_response_at')->selectRaw('AVG(TIMESTAMPDIFF(MINUTE, first_message_at, first_response_at)) value')->value('value')??0),'csat'=>(float)(DB::table('csat_responses')->whereBetween('submitted_at',[$from,$to])->avg('rating')??0),'sla_breaches'=>DB::table('sla_instances')->whereBetween('created_at',[$from,$to])->whereNotNull('breached_at')->count()],'byChannel'=>Conversation::whereBetween('conversations.created_at',[$from,$to])->join('channels','channels.id','=','conversations.channel_id')->selectRaw('channels.name label, count(*) total')->groupBy('channels.id','channels.name')->orderByDesc('total')->get(),'byStatus'=>Conversation::whereBetween('created_at',[$from,$to])->selectRaw('status label, count(*) total')->groupBy('status')->get(),'agents'=>DB::table('users')->leftJoin('conversations','conversations.assignee_id','=','users.id')->where('users.status','active')->selectRaw('users.id, users.name, count(conversations.id) assigned')->groupBy('users.id','users.name')->orderByDesc('assigned')->get()]);}
 public function export(Request $r):StreamedResponse{$this->access($r);[$from,$to]=$this->range($r);return response()->streamDownload(function()use($from,$to):void{$out=fopen('php://output','w');fputcsv($out,['Conversation UUID','Status','Priority','Channel','Created','First response']);Conversation::with('channel:id,name')->whereBetween('created_at',[$from,$to])->orderBy('id')->chunk(500,function($rows)use($out):void{foreach($rows as $x)fputcsv($out,[$x->public_uuid,$x->status,$x->priority,$x->channel?->name,$x->created_at,$x->first_response_at]);});fclose($out);},'conversation-report.csv',['Content-Type'=>'text/csv']);}
}
