import PageHeader from '@/Components/Superadmin/PageHeader';
import Pagination from '@/Components/Superadmin/Pagination';
import { SectionCard } from '@/Components/UI/Card';
import UsageMetrics from '@/Components/UsageMetrics';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';

const features = [['users', 'Users'], ['messages', 'Messages'], ['knowledge_documents', 'Knowledge'], ['automation_rules', 'Automations'], ['api_request_logs', 'API'], ['knowledge_usage_records', 'AI usage'], ['conversation_attachments', 'Storage']];
export default function Index({ tenants, selectedTenant, usage, accounts, plans, filters = {} }) {
    const update = (key, value) => router.get(route('superadmin.usage.index'), { ...filters, [key]: value || undefined }, { preserveState: true, replace: true });
    return <AuthenticatedLayout header={<PageHeader title="Usage" subtitle="Inspect real, supported workspace counters and compare them with service-plan limits." />}><Head title="Usage" /><div className="grid gap-6 xl:grid-cols-[1fr_1.2fr]"><SectionCard title="Services"><div className="mb-4 grid gap-2 sm:grid-cols-2"><input defaultValue={filters.search || ''} onKeyDown={event => event.key === 'Enter' && update('search', event.currentTarget.value)} placeholder="Search service" className="rounded-lg border-slate-300 text-sm" /><select value={filters.account_id || ''} onChange={event => update('account_id', event.target.value)} className="rounded-lg border-slate-300 text-sm"><option value="">All accounts</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select><select value={filters.plan_id || ''} onChange={event => update('plan_id', event.target.value)} className="rounded-lg border-slate-300 text-sm"><option value="">All plans</option>{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select><select value={filters.feature || ''} onChange={event => update('feature', event.target.value)} className="rounded-lg border-slate-300 text-sm"><option value="">All supported features</option>{features.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="divide-y">{tenants.data.map(tenant => <Link key={tenant.id} href={route('superadmin.usage.index', { ...filters, tenant_id: tenant.id })} className={`block py-3 ${selectedTenant?.id === tenant.id ? 'text-indigo-700' : ''}`}><p className="font-semibold">{tenant.company_name}</p><p className="text-xs text-slate-500">{tenant.customer_account?.name || 'Unassigned'} · {tenant.plan?.name || 'No plan'}</p></Link>)}</div><Pagination links={tenants.links} /></SectionCard><SectionCard title={selectedTenant ? `${selectedTenant.company_name} usage` : 'Select a service'} description={selectedTenant ? `${selectedTenant.customer_account?.name || 'Unassigned'} · ${selectedTenant.plan?.name || 'No plan'}` : 'Choose a service to query its tenant database. Counters are never fabricated.'}>{selectedTenant && <div className="mb-4 flex justify-end"><select value={filters.period || 'current_month'} onChange={event => update('period', event.target.value)} className="rounded-lg border-slate-300 text-sm"><option value="today">Today</option><option value="current_month">Current month</option><option value="last_30_days">Last 30 days</option><option value="lifetime">Lifetime</option></select></div>}{selectedTenant ? <UsageMetrics usage={usage} /> : <p className="py-12 text-center text-sm text-slate-500">Select a service from the list.</p>}</SectionCard></div></AuthenticatedLayout>;
}
