<?php
namespace App\Http\Controllers\Tenant\Admin\Automation;
use App\Http\Controllers\Controller; use App\Models\Automation\AutomationLog; use App\Models\Automation\AutomationRule; use App\Models\Productivity\Macro; use App\Models\Productivity\SavedReply; use App\Models\Team; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Inertia\Inertia; use Inertia\Response;
class AutomationController extends Controller
{
 private function access(Request $r,string $permission='automation.view'):void{abort_unless($r->user('tenant')->can($permission),403);}
 public function index(Request $r):Response{$this->access($r);return Inertia::render('Tenant/Admin/Automation/Index',['savedReplies'=>SavedReply::latest()->get(),'macros'=>Macro::latest()->get(),'rules'=>AutomationRule::latest()->get(),'logs'=>AutomationLog::with('rule:id,name')->latest('started_at')->paginate(50),'teams'=>Team::where('status','active')->orderBy('name')->get(['id','name'])]);}
 public function storeReply(Request $r):RedirectResponse{$this->access($r,'productivity.manage');$d=$r->validate(['name'=>['required','string','max:255'],'shortcut'=>['nullable','string','max:64','unique:saved_replies,shortcut'],'scope'=>['required','in:workspace,team,personal'],'team_id'=>['nullable','exists:teams,id'],'subject'=>['nullable','string','max:255'],'body'=>['required','string','max:100000']]);preg_match_all('/{{\s*([a-zA-Z0-9_.]+)\s*}}/',$d['body'],$m);SavedReply::create(array_merge($d,['variables'=>array_values(array_unique($m[1]??[])),'active'=>true,'created_by'=>$r->user('tenant')->id]));return back()->with('status','Saved reply created.');}
 public function storeMacro(Request $r):RedirectResponse{$this->access($r,'productivity.manage');$d=$r->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string'],'resource_type'=>['required','in:conversation,ticket'],'scope'=>['required','in:workspace,team,personal'],'team_id'=>['nullable','exists:teams,id'],'action_type'=>['required','in:set_priority,assign_team,assign_user,set_status,add_tag,create_task,ai_draft_reply'],'action_value'=>['nullable']]);Macro::create(['name'=>$d['name'],'description'=>$d['description']??null,'resource_type'=>$d['resource_type'],'scope'=>$d['scope'],'team_id'=>$d['team_id']??null,'actions'=>[['type'=>$d['action_type'],'value'=>$d['action_value']]],'active'=>true,'created_by'=>$r->user('tenant')->id]);return back()->with('status','Macro created.');}
 public function storeRule(Request $r):RedirectResponse{$this->access($r,'automation.manage');$d=$r->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string'],'trigger'=>['required','in:conversation.created,conversation.updated,message.received,message.sent,ticket.created,ticket.updated,scheduled.hourly,scheduled.daily'],'resource_type'=>['required','in:conversation,ticket'],'priority'=>['required','integer','min:0'],'field'=>['required','in:resource.priority,resource.status,resource.team_id,resource.assignee_id,channel.type,customer.status,customer.language,time.hour,time.weekday'],'operator'=>['required','in:equals,not_equals,in,not_in,contains,greater_than,less_than,is_null,is_not_null'],'condition_value'=>['nullable'],'action_type'=>['required','in:set_priority,assign_team,assign_user,set_status,add_tag,create_task,ai_draft_reply'],'action_value'=>['nullable']]);AutomationRule::create(['name'=>$d['name'],'description'=>$d['description']??null,'trigger'=>$d['trigger'],'resource_type'=>$d['resource_type'],'priority'=>$d['priority'],'active'=>true,'conditions'=>['operator'=>'and','rules'=>[['field'=>$d['field'],'operator'=>$d['operator'],'value'=>$d['condition_value']??null]]],'actions'=>[['type'=>$d['action_type'],'value'=>$d['action_value']]],'created_by'=>$r->user('tenant')->id]);return back()->with('status','Automation rule created.');}
 public function toggle(Request $r,AutomationRule $automationRule):RedirectResponse{$this->access($r,'automation.manage');$automationRule->update(['active'=>!$automationRule->active]);return back()->with('status',$automationRule->active?'Automation enabled.':'Automation disabled.');}
 public function destroyReply(Request $r,SavedReply $savedReply):RedirectResponse{$this->access($r,'productivity.manage');$savedReply->delete();return back()->with('status','Saved reply deleted.');}
 public function destroyMacro(Request $r,Macro $macro):RedirectResponse{$this->access($r,'productivity.manage');$macro->delete();return back()->with('status','Macro deleted.');}
}
