<?php
namespace App\Http\Controllers\Tenant\Admin\Governance;
use App\Http\Controllers\Controller;use App\Models\Customer\Contact;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Inertia\Inertia;use Inertia\Response;
class GovernanceController extends Controller
{
 private function access(Request $r,string $permission='governance.view'):void{abort_unless($r->user('tenant')->can($permission),403);}
 public function index(Request $r):Response{$this->access($r);return Inertia::render('Tenant/Admin/Governance/Index',['apiKeys'=>DB::table('developer_api_keys')->latest()->get()->map(fn($x)=>(array)$x),'apiLogs'=>DB::table('api_request_logs')->latest()->limit(100)->get(),'webhooks'=>DB::table('outbound_webhooks')->latest()->get(['public_uuid','name','url','events','active','created_at']),'deliveries'=>DB::table('outbound_webhook_deliveries')->latest()->limit(100)->get(),'retention'=>DB::table('data_retention_policies')->orderBy('resource_type')->get(),'privacy'=>DB::table('privacy_requests')->leftJoin('contacts','contacts.id','=','privacy_requests.contact_id')->select('privacy_requests.*','contacts.display_name')->latest('requested_at')->get(),'usage'=>['contacts'=>Contact::count(),'storage_bytes'=>$this->directorySize(storage_path('app')),'api_calls_30d'=>DB::table('api_request_logs')->where('created_at','>=',now()->subDays(30))->count(),'webhook_deliveries_30d'=>DB::table('outbound_webhook_deliveries')->where('created_at','>=',now()->subDays(30))->count()],'audit'=>DB::table('activity_logs')->latest()->limit(100)->get()]);}
 public function createKey(Request $r):RedirectResponse{$this->access($r,'developer.manage');$d=$r->validate(['name'=>['required','string','max:255'],'scopes'=>['required','array','min:1'],'scopes.*'=>['in:contacts.read,conversations.read,tickets.read,reports.read,ai.read,ai.run']]);$plain='pb_'.Str::random(48);DB::table('developer_api_keys')->insert(['public_uuid'=>(string)Str::uuid(),'name'=>$d['name'],'token_prefix'=>substr($plain,0,11),'token_hash'=>hash('sha256',$plain),'scopes'=>json_encode($d['scopes']),'created_by'=>$r->user('tenant')->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('api_key',$plain)->with('status','API key created. Copy it now; it will not be shown again.');}
 public function revokeKey(Request $r,string $key):RedirectResponse{$this->access($r,'developer.manage');DB::table('developer_api_keys')->where('public_uuid',$key)->update(['revoked_at'=>now(),'updated_at'=>now()]);return back()->with('status','API key revoked.');}
 public function createWebhook(Request $r):RedirectResponse{$this->access($r,'developer.manage');$d=$r->validate(['name'=>['required','string','max:255'],'url'=>['required','url','max:2048'],'events'=>['required','array','min:1'],'events.*'=>['in:conversation.created,message.received,message.sent,ticket.created,ticket.updated,csat.received']]);$secret=Str::random(48);DB::table('outbound_webhooks')->insert(['public_uuid'=>(string)Str::uuid(),'name'=>$d['name'],'url'=>$d['url'],'events'=>json_encode($d['events']),'secret_encrypted'=>Crypt::encryptString($secret),'active'=>true,'created_by'=>$r->user('tenant')->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('webhook_secret',$secret)->with('status','Webhook created. Copy its signing secret now.');}
 public function saveRetention(Request $r):RedirectResponse{$this->access($r,'security.update');$d=$r->validate(['resource_type'=>['required','in:messages,attachments,api_logs,webhook_logs,audit_logs'],'retain_days'=>['required','integer','min:30','max:3650'],'action'=>['required','in:delete,anonymize'],'active'=>['required','boolean']]);DB::table('data_retention_policies')->updateOrInsert(['resource_type'=>$d['resource_type']],array_merge($d,['updated_by'=>$r->user('tenant')->id,'created_at'=>now(),'updated_at'=>now()]));return back()->with('status','Retention policy saved.');}
 public function createPrivacy(Request $r):RedirectResponse{$this->access($r,'privacy.manage');$d=$r->validate(['contact_id'=>['required','exists:contacts,id'],'type'=>['required','in:export,anonymize,delete'],'notes'=>['nullable','string','max:5000']]);DB::table('privacy_requests')->insert(['public_uuid'=>(string)Str::uuid(),'contact_id'=>$d['contact_id'],'type'=>$d['type'],'status'=>'pending','notes'=>$d['notes']??null,'requested_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','Privacy request queued for reviewed processing.');}
 private function directorySize(string $path):int{$size=0;try{$it=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path,\FilesystemIterator::SKIP_DOTS));foreach($it as $file)if($file->isFile())$size+=$file->getSize();}catch(\Throwable){}return $size;}
}
