import Panel from '@/Components/Portal/Panel';
import PortalLayout from '@/Layouts/PortalLayout';
import { Link, useForm } from '@inertiajs/react';

export default function Profile({ profile }) {
    const form = useForm({ _method: 'put', name: profile.name, email: profile.email, phone: profile.phone || '', timezone: profile.timezone || '', locale: profile.locale || 'en', avatar: null });
    const cls = 'mt-1.5 w-full rounded-lg border-slate-300';
    return <PortalLayout title="Profile" actions={<Link href={route('portal.security')} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Security</Link>}><Panel><form onSubmit={event => { event.preventDefault(); form.post(route('portal.profile.update'), { forceFormData: true, preserveScroll: true, data: { ...form.data, _method: 'put' } }); }} className="grid max-w-3xl gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><div className="flex items-center gap-4">{profile.avatar_url ? <img src={profile.avatar_url} alt="" className="h-16 w-16 rounded-full object-cover" /> : <div className="flex h-16 w-16 items-center justify-center rounded-full bg-indigo-100 text-xl font-bold text-indigo-700">{profile.name.charAt(0)}</div>}<label className="text-sm font-medium">Avatar<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => form.setData('avatar', event.target.files[0])} className="mt-1 block text-sm" /></label></div>{form.errors.avatar && <p className="mt-1 text-xs text-rose-600">{form.errors.avatar}</p>}</div><label className="text-sm font-medium">Name<input className={cls} value={form.data.name} onChange={event => form.setData('name', event.target.value)} />{form.errors.name && <span className="text-xs text-rose-600">{form.errors.name}</span>}</label><label className="text-sm font-medium">Email<input type="email" className={cls} value={form.data.email} onChange={event => form.setData('email', event.target.value)} />{form.errors.email && <span className="text-xs text-rose-600">{form.errors.email}</span>}</label><label className="text-sm font-medium">Phone<input className={cls} value={form.data.phone} onChange={event => form.setData('phone', event.target.value)} /></label><label className="text-sm font-medium">Timezone<input className={cls} placeholder="Asia/Kathmandu" value={form.data.timezone} onChange={event => form.setData('timezone', event.target.value)} /></label><label className="text-sm font-medium">Language<input className={cls} value={form.data.locale} onChange={event => form.setData('locale', event.target.value)} /></label><div className="sm:col-span-2"><button disabled={form.processing} className="rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white">Save profile</button></div></form></Panel></PortalLayout>;
}
