import Money from '@/Components/Portal/Money';
import Panel from '@/Components/Portal/Panel';
import StatusPill from '@/Components/Portal/StatusPill';
import PortalLayout from '@/Layouts/PortalLayout';
import { Link, router } from '@inertiajs/react';

export default function Invoice({ invoice }) {
    const billed = invoice.billing_snapshot || {};
    const payable = !['paid', 'void'].includes(invoice.status);
    return <PortalLayout title={`Invoice ${invoice.number}`}><Panel><div className="mb-5 flex flex-wrap justify-end gap-2"><Link href={route('portal.billing.invoices.download', invoice.id)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Download PDF</Link>{payable && <button onClick={() => router.post(route('portal.billing.invoices.pay', invoice.id), { idempotency_key: crypto.randomUUID() }, { preserveScroll: true })} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Pay invoice</button>}</div><div className="flex flex-col justify-between gap-6 border-b border-slate-200 pb-6 sm:flex-row"><div><h2 className="text-xl font-bold text-slate-950">PromptBot</h2><p className="mt-1 text-sm text-slate-500">{invoice.customer_account?.name}</p></div><div className="sm:text-right"><StatusPill value={invoice.status} /><p className="mt-2 text-sm text-slate-500">Issued {invoice.issued_on || '—'} · Due {invoice.due_on || '—'}</p></div></div>{Object.keys(billed).length > 0 && <div className="mt-6 text-sm"><p className="font-semibold text-slate-900">Bill to</p><p className="mt-1 text-slate-600">{billed.billing_name || billed.company_name}<br />{billed.billing_email}</p></div>}<div className="mt-8 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="py-3">Description</th><th className="py-3">Workspace</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Unit price</th><th className="py-3 text-right">Total</th></tr></thead><tbody className="divide-y">{invoice.items.map(item => <tr key={item.id}><td className="py-4 font-medium">{item.description}</td><td className="py-4 text-slate-500">{item.tenant?.company_name || 'Account'}</td><td className="py-4 text-right">{item.quantity}</td><td className="py-4 text-right"><Money value={item.unit_amount} currency={invoice.currency} /></td><td className="py-4 text-right font-semibold"><Money value={item.total} currency={invoice.currency} /></td></tr>)}</tbody></table></div><div className="ml-auto mt-6 max-w-xs space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><Money value={invoice.subtotal} currency={invoice.currency} /></div><div className="flex justify-between"><span className="text-slate-500">Discount</span><Money value={invoice.discount_total} currency={invoice.currency} /></div><div className="flex justify-between"><span className="text-slate-500">Tax</span><Money value={invoice.tax_total} currency={invoice.currency} /></div><div className="flex justify-between border-t pt-3 text-lg font-bold"><span>Total</span><Money value={invoice.total} currency={invoice.currency} /></div></div></Panel></PortalLayout>;
}
