import Money from '@/Components/Portal/Money';
import Panel from '@/Components/Portal/Panel';
import StatusPill from '@/Components/Portal/StatusPill';
import PortalLayout from '@/Layouts/PortalLayout';
import { Link, usePage } from '@inertiajs/react';

export default function Overview({ subscriptions, monthlyRecurring, outstandingBalance, nextBillingDate, defaultPaymentMethod }) {
    const currency = usePage().props.portal.activeAccount.default_currency;
    return <PortalLayout title="Billing overview"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Monthly recurring', <Money value={monthlyRecurring} currency={currency} />], ['Outstanding', <Money value={outstandingBalance} currency={currency} />], ['Active subscriptions', subscriptions.filter((s) => ['active', 'trial', 'past_due'].includes(s.status)).length], ['Next billing date', nextBillingDate ? new Date(nextBillingDate).toLocaleDateString() : '—']].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>)}</div>
        <div className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_0.8fr]"><Panel title="Subscription breakdown" actions={<Link href={route('portal.billing.subscriptions')} className="text-sm font-semibold text-indigo-600">Manage</Link>}><div className="divide-y divide-slate-100">{subscriptions.length ? subscriptions.map((subscription) => <div key={subscription.id} className="grid grid-cols-[1fr_auto] gap-4 py-4 sm:grid-cols-[1fr_140px_120px_auto]"><div><p className="font-semibold text-slate-900">{subscription.tenant?.company_name}</p><p className="text-sm text-slate-500">{subscription.plan?.name}</p></div><span className="hidden self-center capitalize text-sm text-slate-600 sm:block">{subscription.billing_interval}</span><span className="hidden self-center sm:block"><StatusPill value={subscription.status} /></span><span className="self-center font-semibold"><Money value={subscription.billing_interval === 'yearly' ? subscription.plan?.annual_price : subscription.plan?.monthly_price} currency={subscription.plan?.currency || currency} /></span></div>) : <p className="py-8 text-center text-sm text-slate-500">No subscriptions yet.</p>}</div></Panel><Panel title="Default payment method">{defaultPaymentMethod ? <div><p className="font-semibold capitalize text-slate-900">{defaultPaymentMethod.brand || defaultPaymentMethod.type} •••• {defaultPaymentMethod.last_four}</p><p className="mt-1 text-sm text-slate-500">Expires {defaultPaymentMethod.expires_month}/{defaultPaymentMethod.expires_year}</p></div> : <p className="text-sm text-slate-500">No payment method is stored. Card details are held only by the configured payment provider.</p>}<Link href={route('portal.billing.payment-methods')} className="mt-4 inline-flex text-sm font-semibold text-indigo-600">Payment methods</Link></Panel></div>
    </PortalLayout>;
}
