import Money from '@/Components/Portal/Money';
import Panel from '@/Components/Portal/Panel';
import StatusPill from '@/Components/Portal/StatusPill';
import PortalLayout from '@/Layouts/PortalLayout';
import { Link, router } from '@inertiajs/react';

export default function Payments({ payments }) {
    return <PortalLayout title="Payments"><Panel><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500">{['Reference', 'Invoice', 'Workspace', 'Provider', 'Amount', 'Status', 'Date', ''].map((heading, index) => <th key={index} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{payments.data.map(payment => <tr key={payment.id}><td className="px-3 py-4 font-medium">{payment.provider_reference || '—'}</td><td className="px-3 py-4">{payment.invoice?.number || '—'}</td><td className="px-3 py-4">{payment.tenant?.company_name || 'Account'}</td><td className="px-3 py-4 capitalize">{payment.provider}</td><td className="px-3 py-4 font-semibold"><Money value={payment.amount} currency={payment.currency} /></td><td className="px-3 py-4"><StatusPill value={payment.status} />{payment.status === 'failed' && <p className="mt-1 text-xs text-rose-600">Payment failed</p>}</td><td className="px-3 py-4">{new Date(payment.created_at).toLocaleDateString()}</td><td className="px-3 py-4 text-right">{payment.status === 'failed' && payment.invoice && <div className="flex justify-end gap-3"><button onClick={() => router.post(route('portal.billing.payments.retry', payment.id), { idempotency_key: crypto.randomUUID() }, { preserveScroll: true })} className="font-semibold text-indigo-600">Retry</button><Link href={route('portal.billing.payment-methods')} className="font-semibold text-indigo-600">Update method</Link><Link href={route('portal.support.create')} className="font-semibold text-indigo-600">Support</Link></div>}</td></tr>)}</tbody></table>{!payments.data.length && <p className="py-12 text-center text-sm text-slate-500">No payments yet.</p>}</div></Panel></PortalLayout>;
}
