<?php
namespace App\Services\Sla;
use App\Models\Inbox\Conversation; use App\Models\Sla\EscalationExecution; use App\Models\Sla\EscalationPolicy; use App\Models\Sla\SlaInstance; use App\Models\Ticket\Ticket; use App\Models\User; use App\Services\Automation\ConditionEvaluator; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Throwable;
class EscalationService
{
 public function __construct(private readonly ConditionEvaluator $conditions){}
 public function evaluate():int{$count=0;SlaInstance::whereIn('state',['approaching','breached'])->chunkById(100,function($instances)use(&$count):void{foreach($instances as $sla){$resource=$sla->resource_type==='conversation'?Conversation::find($sla->resource_id):Ticket::find($sla->resource_id);if(!$resource)continue;$ctx=['sla'=>['state'=>$sla->state,'breached'=>$sla->state==='breached'],'resource'=>['type'=>$sla->resource_type,'priority'=>$resource->priority,'team_id'=>$resource->team_id,'assignee_id'=>$resource->assignee_id]];foreach(EscalationPolicy::where('active',true)->orderBy('priority')->get() as $policy){if(!$this->conditions->matches($policy->conditions??[],$ctx))continue;if(EscalationExecution::where('escalation_policy_id',$policy->id)->where('resource_type',$sla->resource_type)->where('resource_id',$resource->id)->where('executed_at','>=',now()->subMinutes($policy->cooldown_minutes))->exists())continue;$this->execute($policy,$resource,$sla->resource_type);$count++;}}});return $count;}
 private function execute(EscalationPolicy $policy,$resource,string $type):void{$execution=EscalationExecution::create(['escalation_policy_id'=>$policy->id,'resource_type'=>$type,'resource_id'=>$resource->id,'status'=>'running','executed_at'=>now()]);$done=[];try{DB::transaction(function()use($policy,$resource,&$done):void{foreach($policy->actions??[] as $action){match($action['type']??null){'set_priority'=>$resource->update(['priority'=>$action['priority']??'urgent']),'assign_team'=>$resource->update(['team_id'=>$action['team_id']??null]),'assign_user'=>$resource->update(['assignee_id'=>$action['user_id']??null]),'notify_user'=>$this->notify((int)($action['user_id']??0),$policy,$resource),default=>null};$done[]=$action;}});$execution->update(['status'=>'completed','actions_executed'=>$done]);}catch(Throwable $e){report($e);$execution->update(['status'=>'failed','error_message'=>$e->getMessage(),'actions_executed'=>$done]);}}
 private function notify(int $id,EscalationPolicy $policy,$resource):void{$u=User::find($id);if(!$u)return;DB::table('notifications')->insert(['id'=>(string)Str::uuid(),'type'=>'sla_escalation','notifiable_type'=>User::class,'notifiable_id'=>$u->id,'data'=>json_encode(['policy'=>$policy->name,'resource_type'=>$resource::class,'resource_id'=>$resource->getRouteKey()]),'created_at'=>now(),'updated_at'=>now()]);}
}
