<?php
namespace App\Services\Sla;
use App\Models\Inbox\Conversation; use App\Models\Sla\SlaInstance; use App\Models\Sla\SlaPolicy; use App\Models\Ticket\Ticket; use App\Services\Automation\ConditionEvaluator; use Illuminate\Database\Eloquent\Model;
class SlaService
{
 public function __construct(private readonly BusinessTimeCalculator $time,private readonly ConditionEvaluator $conditions){}
 public function start(Model $resource):?SlaInstance{$type=$resource instanceof Conversation?'conversation':($resource instanceof Ticket?'ticket':null);if(!$type)return null;$context=['resource'=>['type'=>$type,'priority'=>$resource->priority,'channel_id'=>$resource->channel_id,'team_id'=>$resource->team_id],'customer'=>['status'=>$resource->contact?->status,'company_id'=>$resource->company_id]];$policy=SlaPolicy::where('active',true)->orderBy('priority')->get()->first(fn($p)=>$this->conditions->matches($p->conditions??[],$context));if(!$policy)return null;$targets=$policy->targets[$resource->priority]??$policy->targets['normal']??[];$calendar=$policy->calendar_mode==='business_hours'?$policy->businessHours:null;$now=now();return SlaInstance::updateOrCreate(['resource_type'=>$type,'resource_id'=>$resource->id],['sla_policy_id'=>$policy->id,'priority'=>$resource->priority,'state'=>'healthy','started_at'=>$now,'first_response_due_at'=>isset($targets['first_response'])?$this->time->addMinutes($now,(int)$targets['first_response'],$calendar):null,'next_response_due_at'=>isset($targets['next_response'])?$this->time->addMinutes($now,(int)$targets['next_response'],$calendar):null,'resolution_due_at'=>isset($targets['resolution'])?$this->time->addMinutes($now,(int)$targets['resolution'],$calendar):null]);}
 public function fulfillFirstResponse(Model $resource):void{SlaInstance::where('resource_type',$this->type($resource))->where('resource_id',$resource->id)->whereNull('first_response_fulfilled_at')->update(['first_response_fulfilled_at'=>now()]);}
 public function fulfillResolution(Model $resource):void{SlaInstance::where('resource_type',$this->type($resource))->where('resource_id',$resource->id)->update(['resolution_fulfilled_at'=>now(),'state'=>'fulfilled']);}
 public function evaluate():int{$changed=0;SlaInstance::with('policy')->whereNotIn('state',['fulfilled'])->chunkById(200,function($items)use(&$changed):void{foreach($items as $i){$resource=$this->resource($i);if(!$resource)continue;$status=$resource instanceof Ticket?$resource->status?->category:$resource->status;$pause=in_array($status,$i->policy->pause_statuses??[],true);if($pause&&!$i->paused_at){$i->update(['paused_at'=>now()]);$changed++;continue;}if(!$pause&&$i->paused_at){$seconds=$i->paused_at->diffInSeconds(now());$i->update(['paused_seconds'=>$i->paused_seconds+$seconds,'paused_at'=>null,'first_response_due_at'=>$i->first_response_due_at?->addSeconds($seconds),'next_response_due_at'=>$i->next_response_due_at?->addSeconds($seconds),'resolution_due_at'=>$i->resolution_due_at?->addSeconds($seconds)]);$changed++;}if($i->paused_at)continue;$deadlines=collect([$i->first_response_fulfilled_at?null:$i->first_response_due_at,$i->resolution_fulfilled_at?null:$i->resolution_due_at])->filter();if($deadlines->isEmpty()){if($i->resolution_fulfilled_at)$i->update(['state'=>'fulfilled']);continue;}$nearest=$deadlines->sort()->first();if(now()->gte($nearest)){$i->update(['state'=>'breached','breached_at'=>$i->breached_at??now()]);$changed++;}else{$total=max(1,$i->started_at->diffInSeconds($nearest));$elapsed=$i->started_at->diffInSeconds(now());$state=($elapsed/$total*100)>=$i->policy->approaching_percentage?'approaching':'healthy';if($state!==$i->state){$i->update(['state'=>$state]);$changed++;}}}});return $changed;}
 private function type(Model $r):string{return $r instanceof Conversation?'conversation':'ticket';} private function resource(SlaInstance $i):?Model{return $i->resource_type==='conversation'?Conversation::find($i->resource_id):Ticket::find($i->resource_id);}
}
