<?php
namespace App\Services\Operations;
use App\Models\Inbox\Conversation; use App\Models\Operations\AgentPresence; use App\Models\Operations\AssignmentRule; use App\Models\Operations\SupportQueue; use App\Models\Ticket\Ticket; use App\Models\User; use App\Services\Automation\ConditionEvaluator; use Illuminate\Database\Eloquent\Model; use Illuminate\Support\Facades\DB;
class RoutingService
{
 public function __construct(private readonly ConditionEvaluator $conditions){}
 public function route(Model $resource):void{$type=$resource instanceof Conversation?'conversation':($resource instanceof Ticket?'ticket':null);if(!$type)return;$context=$this->context($resource);foreach(AssignmentRule::where('resource_type',$type)->where('active',true)->orderBy('priority')->get() as $rule){if(!$this->conditions->matches($rule->conditions??[],$context))continue;$this->actions($resource,$rule->actions??[]);if($rule->stop_processing)break;}if(!$resource->team_id){$queue=SupportQueue::where('active',true)->orderBy('priority')->get()->first(fn($q)=>$this->conditions->matches($q->conditions??[],$context));if($queue){$resource->team_id=$queue->team_id;$resource->assignee_id=$this->selectAgent($queue,$type);$resource->save();}}}
 private function actions(Model $r,array $actions):void{foreach($actions as $action){match($action['type']??null){'assign_team'=>$r->team_id=$action['team_id']??null,'assign_user'=>$r->assignee_id=$action['user_id']??null,'set_priority'=>$r->priority=$action['priority']??$r->priority,'assign_queue'=>$this->assignQueue($r,(int)($action['queue_id']??0)),default=>null};}$r->save();}
 private function assignQueue(Model $r,int $id):void{$q=SupportQueue::find($id);if(!$q)return;$r->team_id=$q->team_id;$r->assignee_id=$this->selectAgent($q,$r instanceof Conversation?'conversation':'ticket');}
 private function selectAgent(SupportQueue $q,string $type):?int{if($q->assignment_method==='manual'||!$q->team_id)return null;$agents=User::whereHas('teams',fn($x)=>$x->whereKey($q->team_id))->where('status','active')->whereHas('presence',fn($x)=>$x->whereIn('status',['online','away']))->get();if($agents->isEmpty())return null;if($q->assignment_method==='round_robin'){$sorted=$agents->sortBy('id')->values();$index=$sorted->search(fn($u)=>$u->id===$q->last_assigned_user_id);$agent=$sorted[($index===false?0:$index+1)%$sorted->count()];$q->update(['last_assigned_user_id'=>$agent->id]);return $agent->id;}$counts=$agents->mapWithKeys(fn($u)=>[$u->id=>$type==='conversation'?Conversation::where('assignee_id',$u->id)->whereIn('status',['open','pending','waiting_on_customer'])->count():Ticket::where('assignee_id',$u->id)->whereHas('status',fn($x)=>$x->whereNotIn('category',['resolved','closed']))->count()]);return $counts->sort()->keys()->first();}
 private function context(Model $r):array{return ['resource'=>['type'=>$r instanceof Conversation?'conversation':'ticket','priority'=>$r->priority,'status'=>$r instanceof Ticket?$r->status?->category:$r->status,'channel_id'=>$r->channel_id,'team_id'=>$r->team_id,'assignee_id'=>$r->assignee_id],'customer'=>['status'=>$r->contact?->status,'language'=>$r->contact?->preferred_language,'country'=>$r->contact?->country,'company_id'=>$r->company_id],'channel'=>['type'=>$r->channel?->type]];}
}
