import Money from '@/Components/Portal/Money';
import PageHeader from '@/Components/Superadmin/PageHeader';
import StatusBadge from '@/Components/Superadmin/StatusBadge';
import { SectionCard } from '@/Components/UI/Card';
import Tabs from '@/Components/UI/Tabs';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

const Empty = ({ children = 'No records.' }) => <p className="py-8 text-center text-sm text-slate-500">{children}</p>;
const date = value => value ? new Date(value).toLocaleString() : '—';

export default function Show({ account, notes }) {
    const [tab, setTab] = useState('overview');
    const note = useForm({ type: 'internal', body: '' });
    const limit = useForm({ feature_key: 'workspaces', limit_value: '', unit: 'count', period: '', is_enforced: true });
    const status = useForm({ status: account.status, reason: '' });
    const firstTenant = account.tenants?.[0];
    const metrics = [
        ['MRR', <Money value={account.mrr} currency={account.default_currency} />],
        ['Outstanding', <Money value={account.outstanding} currency={account.default_currency} />],
        ['Total paid', <Money value={account.total_paid} currency={account.default_currency} />],
        ['Services', account.tenants_count], ['Members', account.users_count], ['Open tickets', account.open_support_tickets_count],
    ];
    const tabs = [
        ['overview', 'Overview'], ['services', 'Services', account.tenants.length], ['users', 'Users', account.users.length],
        ['subscriptions', 'Subscriptions', account.subscriptions.length], ['invoices', 'Invoices', account.invoices.length],
        ['payments', 'Payments', account.payments.length], ['support', 'Support', account.support_tickets.length],
        ['activity', 'Activity', account.activities.length], ['notes', 'Notes', notes.length],
    ].map(([value, label, count]) => ({ value, label, count }));
    const actions = <div className="flex flex-wrap items-center gap-2"><StatusBadge status={account.status} /><Link href={route('superadmin.customers.accounts.edit', account.public_uuid)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold">Edit</Link><Link href={route('superadmin.services.create', { account_id: account.id })} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white">Create service</Link><Link href={route('superadmin.billing.invoices.create', { account_id: account.id })} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold">Create invoice</Link>{firstTenant && <Link href={route('superadmin.tickets.create', { tenant_id: firstTenant.id })} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold">Create ticket</Link>}</div>;

    const saveLimit = event => { event.preventDefault(); limit.post(route('superadmin.customers.accounts.limits.store', account.public_uuid), { preserveScroll: true, onSuccess: () => limit.reset('limit_value') }); };
    const addNote = event => { event.preventDefault(); note.post(route('superadmin.customers.accounts.notes.store', account.public_uuid), { onSuccess: () => note.reset('body') }); };

    return <AuthenticatedLayout header={<PageHeader title={account.name} subtitle={`${account.account_number} · Owner: ${account.owner?.name || 'Unassigned'} (${account.owner?.email || 'no email'})`} actions={actions} />}><Head title={account.name} />
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{metrics.map(([key, value]) => <div key={key} className="rounded-lg border bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{key}</p><p className="mt-2 text-xl font-bold text-slate-900">{value}</p></div>)}</div>
        <div className="mt-6 rounded-lg border border-slate-200 bg-white px-4 pt-2"><Tabs items={tabs} active={tab} onChange={setTab} /></div>

        <div className="mt-6">
            {tab === 'overview' && <div className="grid gap-6 xl:grid-cols-3"><SectionCard title="Account identity"><dl className="space-y-3 text-sm">{[['Status', <StatusBadge status={account.status} />], ['Legal name', account.legal_name || '—'], ['Billing email', account.billing_email || '—'], ['Currency', account.default_currency], ['Timezone', account.timezone], ['Billing mode', account.billing_mode?.replaceAll('_', ' ')], ['Created', date(account.created_at)]].map(([key, value]) => <div key={key} className="flex justify-between gap-4"><dt className="text-slate-500">{key}</dt><dd className="text-right font-medium capitalize">{value}</dd></div>)}</dl></SectionCard>
                <SectionCard title="Billing profile"><dl className="space-y-3 text-sm">{[['Name', account.billing_profile?.billing_name], ['Company', account.billing_profile?.company_name], ['Email', account.billing_profile?.billing_email], ['Address', [account.billing_profile?.address_line_1, account.billing_profile?.city, account.billing_profile?.country].filter(Boolean).join(', ')], ['Tax number', account.billing_profile?.tax_number || account.billing_profile?.vat_number]].map(([key, value]) => <div key={key} className="flex justify-between gap-4"><dt className="text-slate-500">{key}</dt><dd className="text-right font-medium">{value || '—'}</dd></div>)}</dl></SectionCard>
                <SectionCard title="Account status" description="A reason is required and recorded in the audit log."><form onSubmit={event => { event.preventDefault(); status.put(route('superadmin.customers.accounts.status', account.public_uuid), { preserveScroll: true }); }} className="space-y-3"><select value={status.data.status} onChange={event => status.setData('status', event.target.value)} className="w-full rounded-lg border-slate-300 text-sm">{['active', 'trial', 'past_due', 'suspended', 'closed'].map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select><textarea required rows="2" placeholder="Reason for this status change" value={status.data.reason} onChange={event => status.setData('reason', event.target.value)} className="w-full rounded-lg border-slate-300 text-sm" />{Object.values(status.errors).map(error => <p key={error} className="text-xs text-rose-600">{error}</p>)}<button disabled={status.processing || status.data.status === account.status} className="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Update status</button></form></SectionCard>
                <SectionCard title="Account-level limits" description="Separate from limits attached to an individual service plan." className="xl:col-span-3"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(account.limits || []).map(item => <div key={item.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span><strong className="capitalize">{item.feature_key.replaceAll('_', ' ')}</strong><span className="block text-xs text-slate-500">{Number(item.limit_value).toLocaleString()} {item.unit}{item.period ? ` / ${item.period}` : ''} · {item.is_enforced ? 'enforcement enabled' : 'monitor only'}</span></span><button type="button" onClick={() => confirm('Remove this account limit?') && router.delete(route('superadmin.customers.accounts.limits.destroy', { account: account.public_uuid, limit: item.id }))} className="text-xs font-semibold text-rose-600">Remove</button></div>)}</div><form onSubmit={saveLimit} className="mt-4 grid gap-2 md:grid-cols-5"><select value={limit.data.feature_key} onChange={event => limit.setData('feature_key', event.target.value)} className="rounded-lg border-slate-300 text-sm">{[['workspaces', 'Workspaces'], ['members', 'Members'], ['messages_per_month', 'Messages'], ['api_requests_per_month', 'API requests'], ['storage_mb', 'Storage'], ['ai_tokens', 'AI tokens']].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input required type="number" min="0.01" step="0.01" placeholder="Limit" value={limit.data.limit_value} onChange={event => limit.setData('limit_value', event.target.value)} className="rounded-lg border-slate-300 text-sm" /><select value={limit.data.unit} onChange={event => limit.setData('unit', event.target.value)} className="rounded-lg border-slate-300 text-sm">{['count', 'MB', 'tokens', 'requests'].map(unit => <option key={unit}>{unit}</option>)}</select><select value={limit.data.period} onChange={event => limit.setData('period', event.target.value)} className="rounded-lg border-slate-300 text-sm"><option value="">No reset</option><option value="day">Per day</option><option value="month">Per month</option><option value="year">Per year</option></select><button disabled={limit.processing} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Save limit</button></form>{Object.values(limit.errors).map(error => <p key={error} className="mt-2 text-xs text-rose-600">{error}</p>)}</SectionCard>
            </div>}

            {tab === 'services' && <SectionCard title="Services">{account.tenants.length ? <div className="divide-y">{account.tenants.map(tenant => <div key={tenant.id} className="flex items-center justify-between py-4"><div><Link href={route('superadmin.tenants.show', tenant.public_uuid)} className="font-semibold hover:text-indigo-600">{tenant.company_name}</Link><p className="text-sm text-slate-500">{tenant.domains?.[0]?.domain || tenant.slug} · {tenant.plan?.name || 'No plan'}</p></div><StatusBadge status={tenant.status} /></div>)}</div> : <Empty />}</SectionCard>}
            {tab === 'users' && <SectionCard title="Portal users" description="Account membership remains separate from tenant helpdesk access.">{account.users.length ? <div className="divide-y">{account.users.map(user => <div key={user.id} className="flex justify-between py-4"><div><p className="font-semibold">{user.name}</p><p className="text-sm text-slate-500">{user.email}</p></div><StatusBadge status={user.pivot.role} /></div>)}</div> : <Empty />}</SectionCard>}
            {tab === 'subscriptions' && <SectionCard title="Subscriptions">{account.subscriptions.length ? <div className="divide-y">{account.subscriptions.map(subscription => <Link key={subscription.id} href={route('superadmin.subscriptions.show', subscription.public_uuid || subscription.id)} className="grid gap-3 py-4 text-sm hover:bg-slate-50 sm:grid-cols-[1fr_1fr_auto_auto]"><span className="font-semibold">{subscription.tenant?.company_name || 'Consolidated'}</span><span>{subscription.plan?.name || 'No plan'}</span><span className="capitalize">{subscription.billing_interval}</span><StatusBadge status={subscription.status} /></Link>)}</div> : <Empty />}</SectionCard>}
            {tab === 'invoices' && <SectionCard title="Invoices">{account.invoices.length ? <div className="divide-y">{account.invoices.map(invoice => <Link key={invoice.id} href={route('superadmin.billing.invoices.show', invoice.id)} className="grid gap-3 py-4 text-sm hover:bg-slate-50 sm:grid-cols-[1fr_auto_auto_auto]"><span className="font-mono font-semibold">{invoice.number}</span><span>{date(invoice.issued_on)}</span><Money value={invoice.total} currency={invoice.currency} /><StatusBadge status={invoice.status} /></Link>)}</div> : <Empty />}</SectionCard>}
            {tab === 'payments' && <SectionCard title="Payments">{account.payments.length ? <div className="divide-y">{account.payments.map(payment => <Link key={payment.id} href={route('superadmin.billing.payments.show', payment.id)} className="grid gap-3 py-4 text-sm hover:bg-slate-50 sm:grid-cols-[1fr_auto_auto_auto]"><span className="font-mono font-semibold">{payment.provider_reference || payment.id.slice(0, 8)}</span><span className="capitalize">{payment.provider?.replaceAll('_', ' ')}</span><Money value={payment.amount} currency={payment.currency} /><StatusBadge status={payment.status} /></Link>)}</div> : <Empty />}</SectionCard>}
            {tab === 'support' && <SectionCard title="Support cases">{account.support_tickets.length ? <div className="divide-y">{account.support_tickets.map(ticket => <Link key={ticket.id} href={route('superadmin.tickets.show', ticket.public_uuid || ticket.id)} className="grid gap-3 py-4 text-sm hover:bg-slate-50 sm:grid-cols-[auto_1fr_auto_auto]"><span className="font-mono">{ticket.number}</span><span className="font-semibold">{ticket.subject}</span><span className="capitalize">{ticket.priority}</span><StatusBadge status={ticket.status} /></Link>)}</div> : <Empty />}</SectionCard>}
            {tab === 'activity' && <SectionCard title="Account activity">{account.activities.length ? <div className="space-y-4">{account.activities.map(activity => <div key={activity.id} className="border-l-2 border-indigo-200 pl-3"><p className="text-sm font-medium">{activity.description || activity.event}</p><p className="text-xs text-slate-500">{date(activity.created_at)}</p></div>)}</div> : <Empty />}</SectionCard>}
            {tab === 'notes' && <SectionCard title="Internal notes" description="Never visible in the customer portal."><form onSubmit={addNote} className="grid gap-3 md:grid-cols-[160px_1fr_auto]"><select value={note.data.type} onChange={event => note.setData('type', event.target.value)} className="rounded-lg border-slate-300 text-sm">{['internal', 'sales', 'billing', 'support'].map(value => <option key={value}>{value}</option>)}</select><textarea required rows="2" value={note.data.body} onChange={event => note.setData('body', event.target.value)} className="rounded-lg border-slate-300 text-sm" /><button disabled={note.processing} className="self-start rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Add note</button></form><div className="mt-5 space-y-4">{notes.map(item => <div key={item.id} className="rounded-lg bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{item.type}</p><p className="mt-1 whitespace-pre-wrap text-sm">{item.body}</p></div>)}</div></SectionCard>}
        </div>
    </AuthenticatedLayout>;
}
