import ApplicationLogo from '@/Components/ApplicationLogo';
import { Head, Link } from '@inertiajs/react';
import { BarChart3, Check, Globe2, Inbox, LockKeyhole, Route, TicketCheck, Workflow } from 'lucide-react';

const features = [
    [Inbox, 'Unified inbox', 'Handle customer conversations from one shared operational timeline.'],
    [TicketCheck, 'Tickets and tasks', 'Track ownership, status, priority, dependencies, and due dates.'],
    [Route, 'Routing and SLA', 'Use explicit assignment, business-hour, and escalation rules.'],
    [Workflow, 'Deterministic automation', 'Build transparent trigger, condition, and action workflows.'],
    [Globe2, 'Customer self-service', 'Publish forms, help content, and satisfaction experiences.'],
    [BarChart3, 'Operational reporting', 'Measure response, resolution, SLA, team, and channel outcomes.'],
];

export default function Welcome() {
    return <div className="min-h-screen bg-white text-slate-900"><Head title="PromptBot — Customer support operations" />
        <header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="flex items-center gap-2 font-bold"><ApplicationLogo className="h-9 w-9" />PromptBot</Link><nav className="flex items-center gap-2 text-sm"><a href="#features" className="hidden px-3 py-2 text-slate-600 sm:block">Features</a><Link href={route('portal.login')} className="rounded-md border border-slate-300 px-4 py-2 font-semibold">Customer login</Link><Link href={route('portal.register')} className="rounded-md bg-slate-950 px-4 py-2 font-semibold text-white">Start free trial</Link></nav></div></header>
        <main><section className="bg-slate-950 px-5 py-20 text-white sm:py-28"><div className="mx-auto max-w-5xl text-center"><p className="text-sm font-semibold uppercase tracking-widest text-indigo-300">Multi-tenant customer support platform</p><h1 className="mt-5 text-4xl font-bold leading-tight sm:text-6xl">Run every customer support workspace with clarity</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">Bring conversations, customers, tickets, service levels, automation, self-service, and reporting into one accountable system.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href={route('portal.register')} className="rounded-md bg-indigo-500 px-6 py-3 font-bold text-white hover:bg-indigo-400">Create customer account</Link><Link href={route('portal.login')} className="rounded-md border border-white/25 px-6 py-3 font-semibold hover:bg-white/10">Sign in</Link></div></div></section>
            <section id="features" className="mx-auto max-w-7xl px-5 py-20"><div className="mx-auto max-w-2xl text-center"><h2 className="text-3xl font-bold">A complete support operating system</h2><p className="mt-3 text-slate-500">Built for customer teams, administrators, and the people they support.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, description]) => <article key={title} className="rounded-xl border bg-white p-6 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-50 text-indigo-700"><Icon className="h-5 w-5" /></span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}</div></section>
            <section className="bg-slate-50 px-5 py-20"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><LockKeyhole className="h-9 w-9 text-indigo-700" /><h2 className="mt-4 text-3xl font-bold">Control your data and workflows</h2><p className="mt-4 leading-7 text-slate-600">Database-per-workspace isolation, scoped roles, encrypted secrets, auditable changes, and explicit automation are built into the operating model.</p></div><div className="grid gap-3 sm:grid-cols-2">{['Separate customer and workspace identities', 'Account-aware billing', 'Scoped multi-workspace access', 'Audited lifecycle actions', 'Secure public forms', 'Responsive customer portal'].map(item => <p key={item} className="flex gap-2 rounded-lg bg-white p-3 text-sm shadow-sm"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</p>)}</div></div></section>
            <section className="px-5 py-20 text-center"><h2 className="text-3xl font-bold">Ready to create your first workspace?</h2><p className="mx-auto mt-3 max-w-xl text-slate-500">One customer login can manage every PromptBot service your organization owns.</p><Link href={route('portal.register')} className="mt-7 inline-block rounded-md bg-slate-950 px-6 py-3 font-bold text-white">Get started</Link></section></main>
        <footer className="border-t px-5 py-8 text-center text-sm text-slate-400">© {new Date().getFullYear()} PromptBot.</footer>
    </div>;
}
