<?php
namespace App\Http\Controllers\Tenant\Admin\Ticket;
use App\Services\Operations\RoutingService; use App\Services\Sla\SlaService; use App\Services\Automation\AutomationExecutionService; use App\Services\Developer\OutboundWebhookService;
use App\Http\Controllers\Controller; use App\Http\Requests\Tenant\Ticket\TicketRequest; use App\Models\Channel\Channel; use App\Models\Customer\Company; use App\Models\Customer\Contact; use App\Models\Customer\CustomField; use App\Models\Customer\Tag; use App\Models\Inbox\Conversation; use App\Models\Team; use App\Models\Ticket\Ticket; use App\Models\Ticket\TicketCategory; use App\Models\Ticket\TicketStatus; use App\Models\User; use App\Services\Customer\CustomFieldValueService; use App\Services\Ticket\TicketActivityService; use App\Services\Ticket\TicketMergeService; use App\Services\Ticket\TicketNumberService; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Arr; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Gate; use Inertia\Inertia; use Inertia\Response;
class TicketController extends Controller
{
 public function __construct(private readonly TicketNumberService $numbers,private readonly TicketActivityService $activity,private readonly TicketMergeService $merger,private readonly CustomFieldValueService $customFields,private readonly RoutingService $routing,private readonly SlaService $sla,private readonly AutomationExecutionService $automation,private readonly OutboundWebhookService $webhooks){}
 public function index(Request $r):Response {Gate::authorize('viewAny',Ticket::class);$f=$r->validate(['view'=>['nullable','in:all,mine,unassigned,open,pending,resolved,closed'],'search'=>['nullable','string','max:255'],'status'=>['nullable','integer'],'priority'=>['nullable','in:low,normal,high,urgent'],'team'=>['nullable','integer']]);$q=Ticket::query()->with(['contact:id,public_uuid,display_name,email','status:id,name,category,color','assignee:id,name','team:id,name','category:id,name'])->when(($f['view']??null)==='mine',fn($q)=>$q->where('assignee_id',$r->user('tenant')->id))->when(($f['view']??null)==='unassigned',fn($q)=>$q->whereNull('assignee_id'))->when(in_array($f['view']??'',['open','pending','resolved','closed'],true),fn($q)=>$q->whereHas('status',fn($q)=>$q->where('category',$f['view'])))->when($f['search']??null,fn($q,$s)=>$q->where(fn($q)=>$q->where('ticket_number','like',"%{$s}%")->orWhere('subject','like',"%{$s}%")->orWhereHas('contact',fn($q)=>$q->where('display_name','like',"%{$s}%"))))->when($f['status']??null,fn($q,$v)=>$q->where('status_id',$v))->when($f['priority']??null,fn($q,$v)=>$q->where('priority',$v))->when($f['team']??null,fn($q,$v)=>$q->where('team_id',$v));return Inertia::render('Tenant/Admin/Tickets/Index',['tickets'=>$q->latest('updated_at')->paginate(25)->withQueryString(),'filters'=>$f,'statuses'=>TicketStatus::where('active',true)->orderBy('display_order')->get(),'teams'=>Team::where('status','active')->orderBy('name')->get(['id','name'])]);}
 public function create(Request $r):Response {Gate::authorize('create',Ticket::class);return Inertia::render('Tenant/Admin/Tickets/Form',array_merge($this->formData(),['ticket'=>null,'preset'=>['contact_id'=>$r->integer('contact')?:'','conversation_id'=>$r->integer('conversation')?:'']]));}
 public function store(TicketRequest $r):RedirectResponse {$ticket=DB::transaction(function()use($r):Ticket{$d=$r->validated();$d['ticket_number']=$this->numbers->next();$d['created_by']=$r->user('tenant')->id;$d['source']??='manual';$t=Ticket::create(Arr::except($d,['tag_ids','custom_fields']));$t->tags()->sync(collect($d['tag_ids']??[])->mapWithKeys(fn($id)=>[$id=>['assigned_by'=>$r->user('tenant')->id]])->all());$this->customFields->validateAndStore($t,'ticket',$d['custom_fields']??[]);$this->activity->record($t,'ticket.created',"Ticket {$t->ticket_number} created.",$r->user('tenant'),new:$d);$this->routing->route($t);$this->sla->start($t);$this->automation->dispatch('ticket.created',$t->fresh());$this->webhooks->record('ticket.created',$t);return $t;});return redirect()->route('tenant.admin.tickets.show',$ticket)->with('status','Ticket created.');}
 public function show(Ticket $ticket):Response {Gate::authorize('view',$ticket);if($ticket->merged_into_id){$destination=Ticket::find($ticket->merged_into_id);if($destination)return redirect()->route('tenant.admin.tickets.show',$destination)->with('status',"{$ticket->ticket_number} was merged into this ticket.");}$ticket->load(['contact.company','company','conversation','channel','team','assignee','status','category.parent','comments.user:id,name','activities.actor:id,name','tags','customFieldValues.field']);return Inertia::render('Tenant/Admin/Tickets/Show',['ticket'=>$ticket,'users'=>User::where('status','active')->orderBy('name')->get(['id','name']),'teams'=>Team::where('status','active')->orderBy('name')->get(['id','name']),'statuses'=>TicketStatus::where('active',true)->orderBy('display_order')->get(['id','name','category','color']),'mergeCandidates'=>Ticket::whereKeyNot($ticket->id)->whereNull('merged_into_id')->latest()->limit(50)->get(['id','public_uuid','ticket_number','subject'])]);}
 public function edit(Ticket $ticket):Response {Gate::authorize('update',$ticket);return Inertia::render('Tenant/Admin/Tickets/Form',array_merge($this->formData(),['ticket'=>$ticket->load('tags:id'),'preset'=>[],'customValues'=>$ticket->customFieldValues()->with('field:id,key')->get()->mapWithKeys(fn($v)=>[$v->field->key=>$v->value])]));}
 public function update(TicketRequest $r,Ticket $ticket):RedirectResponse {DB::transaction(function()use($r,$ticket):void{$old=$ticket->toArray();$d=$r->validated();$status=TicketStatus::findOrFail($d['status_id']);$d['resolved_at']=$status->category==='resolved'?($ticket->resolved_at??now()):null;$d['closed_at']=$status->category==='closed'?($ticket->closed_at??now()):null;$ticket->update(Arr::except($d,['tag_ids','custom_fields']));$ticket->tags()->sync(collect($d['tag_ids']??[])->mapWithKeys(fn($id)=>[$id=>['assigned_by'=>$r->user('tenant')->id]])->all());$this->customFields->validateAndStore($ticket,'ticket',$d['custom_fields']??[]);$this->activity->record($ticket,'ticket.updated','Ticket updated.',$r->user('tenant'),$old,$d);if(in_array($status->category,['resolved','closed'],true)){$this->sla->fulfillResolution($ticket);}$this->automation->dispatch('ticket.updated',$ticket->fresh());});return redirect()->route('tenant.admin.tickets.show',$ticket)->with('status','Ticket updated.');}
 public function comment(Request $r,Ticket $ticket):RedirectResponse {Gate::authorize('update',$ticket);$d=$r->validate(['body'=>['required','string','max:50000'],'internal'=>['required','boolean']]);$ticket->comments()->create(['user_id'=>$r->user('tenant')->id,'author_name'=>$r->user('tenant')->name,'body'=>$d['body'],'internal'=>$d['internal']]);$this->activity->record($ticket,'ticket.comment_added',$d['internal']?'Internal comment added.':'Public comment added.',$r->user('tenant'));return back()->with('status','Comment added.');}
 public function merge(Request $r,Ticket $ticket):RedirectResponse {Gate::authorize('merge',$ticket);$d=$r->validate(['destination_id'=>['required','exists:tickets,id'],'reason'=>['nullable','string','max:2000']]);$destination=Ticket::findOrFail($d['destination_id']);$this->merger->merge($ticket,$destination,$r->user('tenant'),$d['reason']??null);return redirect()->route('tenant.admin.tickets.show',$destination)->with('status','Tickets merged.');}
 public function destroy(Ticket $ticket):RedirectResponse {Gate::authorize('delete',$ticket);$ticket->delete();$this->activity->record($ticket,'ticket.archived','Ticket archived.');return redirect()->route('tenant.admin.tickets.index')->with('status','Ticket archived.');}
 private function formData():array{return ['contacts'=>Contact::orderBy('display_name')->limit(1000)->get(['id','display_name','email','company_id']),'companies'=>Company::orderBy('name')->get(['id','name']),'conversations'=>Conversation::latest('last_message_at')->limit(100)->get(['id','public_uuid','subject','contact_id']),'channels'=>Channel::where('status','active')->orderBy('name')->get(['id','name','type']),'teams'=>Team::where('status','active')->orderBy('name')->get(['id','name']),'users'=>User::where('status','active')->orderBy('name')->get(['id','name']),'statuses'=>TicketStatus::where('active',true)->orderBy('display_order')->get(),'categories'=>TicketCategory::where('active',true)->with('parent:id,name')->orderBy('display_order')->get(),'tags'=>Tag::where('status','active')->orderBy('name')->get(['id','name','color']),'customFields'=>CustomField::where('resource_type','ticket')->where('active',true)->orderBy('display_order')->get(),'customValues'=>[]];}
}
