<?php
namespace App\Http\Controllers\Tenant\Admin\Ticket;
use App\Http\Controllers\Controller; use App\Models\Ticket\TicketCategory; use App\Models\Ticket\TicketStatus; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Str; use Illuminate\Validation\Rule; use Inertia\Inertia; use Inertia\Response;
class TicketSettingsController extends Controller
{
 private function authorizeSettings(Request $r):void{abort_unless($r->user('tenant')->can('tickets.settings.manage'),403);}
 public function index(Request $r):Response{$this->authorizeSettings($r);return Inertia::render('Tenant/Admin/Tickets/Settings',['statuses'=>TicketStatus::withCount('tickets')->orderBy('display_order')->get(),'categories'=>TicketCategory::with(['parent:id,name'])->withCount('tickets')->orderBy('display_order')->get()]);}
 public function storeStatus(Request $r):RedirectResponse{$this->authorizeSettings($r);$d=$r->validate(['name'=>['required','string','max:120'],'category'=>['required','in:new,open,pending,waiting_on_customer,resolved,closed'],'color'=>['required','regex:/^#[0-9a-fA-F]{6}$/']]);TicketStatus::create(array_merge($d,['slug'=>$this->uniqueSlug($d['name'],TicketStatus::class),'display_order'=>TicketStatus::max('display_order')+10]));return back()->with('status','Ticket status created.');}
 public function updateStatus(Request $r,TicketStatus $status):RedirectResponse{$this->authorizeSettings($r);$d=$r->validate(['name'=>['required','string','max:120'],'category'=>['required','in:new,open,pending,waiting_on_customer,resolved,closed'],'color'=>['required','regex:/^#[0-9a-fA-F]{6}$/'],'active'=>['required','boolean']]);if(!$d['active']&&$status->tickets()->whereNull('deleted_at')->exists())return back()->withErrors(['active'=>'Reassign tickets before archiving this status.']);$status->update($d);return back()->with('status','Ticket status updated.');}
 public function storeCategory(Request $r):RedirectResponse{$this->authorizeSettings($r);$d=$r->validate(['name'=>['required','string','max:120'],'parent_id'=>['nullable','exists:ticket_categories,id'],'description'=>['nullable','string','max:1000']]);TicketCategory::create(array_merge($d,['slug'=>$this->uniqueSlug($d['name'],TicketCategory::class),'display_order'=>TicketCategory::max('display_order')+10]));return back()->with('status','Ticket category created.');}
 public function updateCategory(Request $r,TicketCategory $category):RedirectResponse{$this->authorizeSettings($r);$d=$r->validate(['name'=>['required','string','max:120'],'parent_id'=>['nullable','exists:ticket_categories,id',Rule::notIn([$category->id])],'description'=>['nullable','string','max:1000'],'active'=>['required','boolean']]);$category->update($d);return back()->with('status','Ticket category updated.');}
 private function uniqueSlug(string $name,string $model):string{$base=Str::slug($name);$slug=$base;$i=1;while($model::where('slug',$slug)->exists())$slug=$base.'-'.++$i;return $slug;}
}
