<?php
namespace App\Http\Controllers\Tenant;
use App\Http\Controllers\Controller;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Inertia\Inertia;use Inertia\Response;
class PublicSupportController extends Controller
{
 public function help(Request $r):Response{$settings=DB::table('help_center_settings')->where('active',true)->first();abort_unless($settings,404);$q=trim((string)$r->query('q'));$articles=DB::table('knowledge_faqs')->where('status','published')->whereNull('deleted_at')->when($q,fn($x)=>$x->where(fn($x)=>$x->where('question','like',"%{$q}%")->orWhere('answer','like',"%{$q}%")))->orderByDesc('priority')->paginate(20);return Inertia::render('Tenant/Public/HelpCenter',['settings'=>$settings,'articles'=>$articles,'query'=>$q,'forms'=>DB::table('support_forms')->where('active',true)->get(['slug','name'])]);}
 public function form(string $slug):Response{$form=DB::table('support_forms')->where('slug',$slug)->where('active',true)->first();abort_unless($form,404);return Inertia::render('Tenant/Public/SupportForm',['form'=>$form,'fields'=>DB::table('support_form_fields')->where('support_form_id',$form->id)->orderBy('display_order')->get()]);}
 public function submit(Request $r,string $slug):RedirectResponse{$form=DB::table('support_forms')->where('slug',$slug)->where('active',true)->first();abort_unless($form,404);$fields=DB::table('support_form_fields')->where('support_form_id',$form->id)->get();$rules=[];foreach($fields as $field)$rules[$field->key]=array_filter([$field->required?'required':'nullable',match($field->type){'email'=>'email','number'=>'numeric',default=>'string'},'max:50000']);$data=$r->validate($rules);$contactId=null;if($email=$data['email']??null){$contactId=DB::table('contacts')->where('email',$email)->value('id')??DB::table('contacts')->insertGetId(['public_uuid'=>(string)Str::uuid(),'display_name'=>$data['name']??$email,'email'=>$email,'status'=>'active','source'=>'form','created_at'=>now(),'updated_at'=>now()]);}DB::table('support_form_submissions')->insert(['public_uuid'=>(string)Str::uuid(),'support_form_id'=>$form->id,'contact_id'=>$contactId,'payload'=>json_encode($data),'status'=>'received','ip_hash'=>hash('sha256',(string)$r->ip().config('app.key')),'submitted_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('status',json_decode($form->settings??'{}',true)['success_message']??'Your request has been received.');}
 public function csat(Request $r,string $survey,string $resourceType,int $resourceId):RedirectResponse{$record=DB::table('csat_surveys')->where('public_uuid',$survey)->where('active',true)->first();abort_unless($record&&$record->resource_type===$resourceType,404);$d=$r->validate(['rating'=>['required','integer','min:1','max:'.$record->scale],'comment'=>['nullable','string','max:5000']]);DB::table('csat_responses')->insert(['public_uuid'=>(string)Str::uuid(),'csat_survey_id'=>$record->id,'resource_type'=>$resourceType,'resource_id'=>$resourceId,'rating'=>$d['rating'],'comment'=>$d['comment']??null,'response_token_hash'=>hash('sha256',$r->fullUrl()),'submitted_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','Thank you for your feedback.');}
 public function portal(string $token):Response{$record=DB::table('customer_portal_tokens')->where('token_hash',hash('sha256',$token))->whereNull('revoked_at')->where('expires_at','>',now())->first();abort_unless($record,404);DB::table('customer_portal_tokens')->where('id',$record->id)->update(['last_used_at'=>now(),'updated_at'=>now()]);$contact=DB::table('contacts')->where('id',$record->contact_id)->first();return Inertia::render('Tenant/Public/Portal',['contact'=>$contact,'tickets'=>DB::table('tickets')->join('ticket_statuses','ticket_statuses.id','=','tickets.status_id')->where('tickets.contact_id',$record->contact_id)->select('tickets.public_uuid','tickets.ticket_number','tickets.subject','tickets.priority','ticket_statuses.name as status','tickets.created_at','tickets.updated_at')->latest('tickets.updated_at')->get(),'conversations'=>DB::table('conversations')->where('contact_id',$record->contact_id)->select('public_uuid','subject','status','priority','last_message_at')->latest('last_message_at')->get()]);}
}
