<?php
namespace App\Http\Controllers\Tenant\Admin\Quality;use App\Http\Controllers\Controller;use App\Models\User;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Inertia\Inertia;use Inertia\Response;
class QualityWorkforceController extends Controller
{
 private function access(Request $r,string $permission):void{abort_unless($r->user('tenant')->can($permission),403);}public function index(Request $r,string $mode='quality'):Response{$permission=$mode==='workforce'?'workforce.view':'quality.view';$this->access($r,$permission);return Inertia::render('Tenant/Admin/Quality/Index',['mode'=>$mode,'scorecards'=>DB::table('qa_scorecards')->latest()->get(),'reviews'=>DB::table('qa_reviews')->join('users as agents','agents.id','=','qa_reviews.agent_id')->join('users as reviewers','reviewers.id','=','qa_reviews.reviewer_id')->select('qa_reviews.*','agents.name as agent_name','reviewers.name as reviewer_name')->latest('reviewed_at')->get(),'coaching'=>DB::table('coaching_sessions')->join('users as agents','agents.id','=','coaching_sessions.agent_id')->select('coaching_sessions.*','agents.name as agent_name')->latest()->get(),'shifts'=>DB::table('workforce_shifts')->join('users','users.id','=','workforce_shifts.user_id')->select('workforce_shifts.*','users.name as user_name')->orderByDesc('starts_at')->get(),'timeOff'=>DB::table('time_off_requests')->join('users','users.id','=','time_off_requests.user_id')->select('time_off_requests.*','users.name as user_name')->latest()->get(),'users'=>User::where('status','active')->orderBy('name')->get(['id','name'])]);}
 public function storeScorecard(Request $r):RedirectResponse{$this->access($r,'quality.manage');$d=$r->validate(['name'=>['required','string','max:255'],'criteria'=>['required','string','max:5000'],'passing_score'=>['required','integer','min:1','max:100']]);$criteria=collect(preg_split('/\r?\n/',$d['criteria']))->filter()->values()->map(fn($x)=>['name'=>$x,'weight'=>1])->all();DB::table('qa_scorecards')->insert(['public_uuid'=>(string)Str::uuid(),'name'=>$d['name'],'criteria'=>json_encode($criteria),'passing_score'=>$d['passing_score'],'active'=>true,'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','QA scorecard created.');}
 public function storeReview(Request $r):RedirectResponse{$this->access($r,'quality.manage');$d=$r->validate(['qa_scorecard_id'=>['required','exists:qa_scorecards,id'],'resource_type'=>['required','in:conversation,ticket'],'resource_id'=>['required','integer','min:1'],'agent_id'=>['required','exists:users,id'],'total_score'=>['required','integer','min:0','max:100'],'feedback'=>['nullable','string','max:10000']]);DB::table('qa_reviews')->insert(array_merge($d,['public_uuid'=>(string)Str::uuid(),'reviewer_id'=>$r->user('tenant')->id,'scores'=>json_encode(['overall'=>$d['total_score']]),'status'=>'completed','reviewed_at'=>now(),'created_at'=>now(),'updated_at'=>now()]));return back()->with('status','QA review recorded.');}
 public function storeShift(Request $r):RedirectResponse{$this->access($r,'workforce.manage');$d=$r->validate(['user_id'=>['required','exists:users,id'],'starts_at'=>['required','date'],'ends_at'=>['required','date','after:starts_at'],'timezone'=>['required','timezone'],'notes'=>['nullable','string','max:2000']]);DB::table('workforce_shifts')->insert(array_merge($d,['public_uuid'=>(string)Str::uuid(),'status'=>'scheduled','created_by'=>$r->user('tenant')->id,'created_at'=>now(),'updated_at'=>now()]));return back()->with('status','Shift scheduled.');}
 public function requestTimeOff(Request $r):RedirectResponse{$this->access($r,'workforce.view');$d=$r->validate(['starts_on'=>['required','date'],'ends_on'=>['required','date','after_or_equal:starts_on'],'type'=>['required','in:vacation,sick,personal,other'],'reason'=>['nullable','string','max:2000']]);DB::table('time_off_requests')->insert(array_merge($d,['public_uuid'=>(string)Str::uuid(),'user_id'=>$r->user('tenant')->id,'status'=>'pending','created_at'=>now(),'updated_at'=>now()]));return back()->with('status','Time off request submitted.');}
}
