<?php
namespace App\Http\Controllers\Tenant\Admin\Task;
use App\Http\Controllers\Controller; use App\Http\Requests\Tenant\Task\TaskRequest; use App\Models\Customer\Company; use App\Models\Customer\Contact; use App\Models\Customer\Tag; use App\Models\Inbox\Conversation; use App\Models\Task\Task; use App\Models\Ticket\Ticket; use App\Models\User; use App\Services\Tenant\TenantAuditLogService; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Arr; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Gate; use Illuminate\Validation\ValidationException; use Inertia\Inertia; use Inertia\Response;
class TaskController extends Controller
{
 public function __construct(private readonly TenantAuditLogService $audit){}
 public function index(Request $r):Response {Gate::authorize('viewAny',Task::class);$f=$r->validate(['view'=>['nullable','in:mine,all,today,upcoming,overdue,completed'],'search'=>['nullable','string','max:255'],'status'=>['nullable','in:todo,in_progress,blocked,completed,cancelled'],'priority'=>['nullable','in:low,normal,high,urgent'],'assignee'=>['nullable','integer']]);$view=$f['view']??'mine';$q=Task::query()->with(['assignee:id,name','creator:id,name','subtasks:id,parent_task_id,status'])->when($view==='mine',fn($q)=>$q->where('assigned_to',$r->user('tenant')->id))->when($view==='today',fn($q)=>$q->whereDate('due_at',today())->whereNotIn('status',['completed','cancelled']))->when($view==='upcoming',fn($q)=>$q->where('due_at','>',today()->endOfDay())->whereNotIn('status',['completed','cancelled']))->when($view==='overdue',fn($q)=>$q->where('due_at','<',now())->whereNotIn('status',['completed','cancelled']))->when($view==='completed',fn($q)=>$q->where('status','completed'))->when($f['search']??null,fn($q,$s)=>$q->where('title','like',"%{$s}%"))->when($f['status']??null,fn($q,$v)=>$q->where('status',$v))->when($f['priority']??null,fn($q,$v)=>$q->where('priority',$v))->when($f['assignee']??null,fn($q,$v)=>$q->where('assigned_to',$v));return Inertia::render('Tenant/Admin/Tasks/Index',['tasks'=>$q->orderByRaw('due_at IS NULL')->orderBy('due_at')->paginate(30)->withQueryString(),'filters'=>$f,'users'=>User::where('status','active')->orderBy('name')->get(['id','name'])]);}
 public function create(Request $r):Response {Gate::authorize('create',Task::class);return Inertia::render('Tenant/Admin/Tasks/Form',array_merge($this->formData(),['task'=>null,'preset'=>['related_type'=>$r->string('related_type')->toString(),'related_id'=>$r->integer('related_id')?:'','parent_task_id'=>$r->integer('parent_task_id')?:'']]));}
 public function store(TaskRequest $r):RedirectResponse {$d=$r->validated();$this->validateRelated($d);$d['created_by']=$r->user('tenant')->id;$task=DB::transaction(function()use($d,$r){$t=Task::create(Arr::except($d,'tag_ids'));$t->tags()->sync(collect($d['tag_ids']??[])->mapWithKeys(fn($id)=>[$id=>['assigned_by'=>$r->user('tenant')->id]])->all());return $t;});$this->audit->record('task.created',description:"Created task \"{$task->title}\"",subject:$task,newValues:$d);return redirect()->route('tenant.admin.tasks.show',$task)->with('status','Task created.');}
 public function show(Task $task):Response {Gate::authorize('view',$task);$task->load(['assignee:id,name,email','creator:id,name','parent:id,public_uuid,title','subtasks.assignee:id,name','tags']);return Inertia::render('Tenant/Admin/Tasks/Show',['task'=>$task,'related'=>$this->relatedResource($task->related_type,$task->related_id)]);}
 public function edit(Task $task):Response {Gate::authorize('update',$task);return Inertia::render('Tenant/Admin/Tasks/Form',array_merge($this->formData(),['task'=>$task->load('tags:id'),'preset'=>[]]));}
 public function update(TaskRequest $r,Task $task):RedirectResponse {$d=$r->validated();$this->validateRelated($d);$old=$task->toArray();if($d['status']==='completed'&&!$task->completed_at)$d['completed_at']=now();elseif($d['status']!=='completed')$d['completed_at']=null;DB::transaction(function()use($task,$d,$r):void{$task->update(Arr::except($d,'tag_ids'));$task->tags()->sync(collect($d['tag_ids']??[])->mapWithKeys(fn($id)=>[$id=>['assigned_by'=>$r->user('tenant')->id]])->all());});$this->audit->record('task.updated',description:"Updated task \"{$task->title}\"",subject:$task,oldValues:$old,newValues:$d);return redirect()->route('tenant.admin.tasks.show',$task)->with('status','Task updated.');}
 public function destroy(Task $task):RedirectResponse {Gate::authorize('delete',$task);$task->delete();$this->audit->record('task.archived',description:"Archived task \"{$task->title}\"",subject:$task);return redirect()->route('tenant.admin.tasks.index')->with('status','Task archived.');}
 private function validateRelated(array $d):void {if(empty($d['related_type'])&&empty($d['related_id']))return;if(empty($d['related_type'])||empty($d['related_id'])||!$this->relatedResource($d['related_type'],$d['related_id']))throw ValidationException::withMessages(['related_id'=>'Select a valid related resource.']);}
 private function relatedResource(?string $type,?int $id):mixed {if(!$type||!$id)return null;$model=match($type){'contact'=>Contact::class,'company'=>Company::class,'ticket'=>Ticket::class,'conversation'=>Conversation::class,default=>null};return $model? $model::find($id):null;}
 private function formData():array{return ['users'=>User::where('status','active')->orderBy('name')->get(['id','name']),'parentTasks'=>Task::whereNotIn('status',['completed','cancelled'])->orderBy('title')->limit(200)->get(['id','title']),'tags'=>Tag::where('status','active')->orderBy('name')->get(['id','name']),'relatedOptions'=>['contact'=>Contact::orderBy('display_name')->limit(200)->get(['id','display_name as label']),'company'=>Company::orderBy('name')->limit(200)->get(['id','name as label']),'ticket'=>Ticket::latest()->limit(200)->get(['id',DB::raw("CONCAT(ticket_number, ' — ', subject) as label")]),'conversation'=>Conversation::latest('last_message_at')->limit(200)->get(['id',DB::raw("COALESCE(subject, CONCAT('Conversation #', id)) as label")])]];}
}
