import Pagination from '@/Components/Superadmin/Pagination';
import CustomersShell from '@/Components/Tenant/Customers/CustomersShell';
import Badge from '@/Components/UI/Badge';
import Button from '@/Components/UI/Button';
import FormField from '@/Components/UI/FormField';
import Input from '@/Components/UI/Input';
import Select from '@/Components/UI/Select';
import { Head, useForm } from '@inertiajs/react';
import { Plus } from 'lucide-react';

export default function Index({ fields, resourceTypes, fieldTypes }) {
    const form = useForm({ label: '', key: '', resource_type: 'contact', field_type: 'text', required: false, options: [], display_order: 0, active: true });
    const submit = (e) => { e.preventDefault(); form.post(route('tenant.admin.customers.custom-fields.store'), { preserveScroll: true, onSuccess: () => form.reset('label', 'key') }); };
    return <CustomersShell title="Custom fields" description="Validated workspace-specific fields shared across support resources."><Head title="Custom fields" /><div className="grid gap-5 lg:grid-cols-[380px,1fr]"><form onSubmit={submit} className="h-fit space-y-4 rounded-lg border border-slate-200 bg-white p-5 shadow-soft"><h2 className="flex items-center gap-2 text-sm font-semibold"><Plus className="h-4 w-4" />Create field</h2><FormField label="Label" required error={form.errors.label}><Input value={form.data.label} onChange={(e) => form.setData('label', e.target.value)} /></FormField><FormField label="Key" hint="Generated from the label when blank." error={form.errors.key}><Input value={form.data.key} onChange={(e) => form.setData('key', e.target.value)} /></FormField><FormField label="Resource"><Select value={form.data.resource_type} onChange={(e) => form.setData('resource_type', e.target.value)}>{resourceTypes.map((x) => <option key={x}>{x}</option>)}</Select></FormField><FormField label="Field type"><Select value={form.data.field_type} onChange={(e) => form.setData('field_type', e.target.value)}>{fieldTypes.map((x) => <option key={x} value={x}>{x.replaceAll('_', ' ')}</option>)}</Select></FormField>{['single_select', 'multi_select'].includes(form.data.field_type) && <FormField label="Options" hint="Comma-separated"><Input value={form.data.options.join(', ')} onChange={(e) => form.setData('options', e.target.value.split(',').map((x) => x.trim()).filter(Boolean))} /></FormField>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.required} onChange={(e) => form.setData('required', e.target.checked)} />Required</label><Button type="submit" variant="brand" loading={form.processing}>Create field</Button></form><div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-soft"><table className="min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">Field</th><th className="px-4 py-3 text-left">Resource</th><th className="px-4 py-3 text-left">Type</th><th className="px-4 py-3 text-left">State</th></tr></thead><tbody className="divide-y divide-slate-100">{fields.data.map((field) => <tr key={field.public_uuid}><td className="px-4 py-3"><span className="font-medium">{field.label}</span><p className="font-mono text-xs text-slate-500">{field.key}</p></td><td className="px-4 py-3 capitalize">{field.resource_type}</td><td className="px-4 py-3">{field.field_type.replaceAll('_', ' ')}</td><td className="px-4 py-3"><Badge tone={field.active ? 'brand' : 'neutral'}>{field.active ? 'Active' : 'Archived'}</Badge></td></tr>)}</tbody></table><Pagination links={fields.links} /></div></div></CustomersShell>;
}
