import Pagination from '@/Components/Superadmin/Pagination';
import Avatar from '@/Components/UI/Avatar';
import Badge from '@/Components/UI/Badge';
import EmptyState from '@/Components/UI/EmptyState';
import SearchInput from '@/Components/UI/SearchInput';
import Select from '@/Components/UI/Select';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { Inbox } from 'lucide-react';
import { useState } from 'react';

const views = [['all','All'],['mine','Mine'],['unassigned','Unassigned'],['mentions','Mentions'],['snoozed','Snoozed'],['open','Open'],['pending','Pending'],['closed','Closed']];
const priorityTone = { urgent: 'danger', high: 'warning', normal: 'neutral', low: 'neutral' };
export default function Index({ conversations, filters, teams, channels }) {
    const [search,setSearch]=useState(filters.search||''); const apply=(next={})=>router.get(route('tenant.admin.inbox.index'),{...filters,search,...next},{preserveState:true,preserveScroll:true});
    return <AuthenticatedLayout title="Inbox"><Head title="Inbox" /><div className="grid min-h-[calc(100vh-7rem)] overflow-hidden rounded-lg border border-slate-200 bg-white shadow-soft lg:grid-cols-[210px,1fr]"><aside className="border-b border-slate-200 bg-slate-50 p-3 lg:border-b-0 lg:border-r"><h1 className="px-2 py-2 text-sm font-bold text-navy-900">Inbox</h1><nav className="space-y-1">{views.map(([key,label])=><button key={key} type="button" onClick={()=>apply({view:key})} className={`block w-full rounded-md px-3 py-2 text-left text-sm font-medium ${(filters.view||'all')===key?'bg-white text-brand-700 shadow-soft':'text-slate-600 hover:bg-white'}`}>{label}</button>)}</nav></aside><section className="min-w-0"><div className="flex flex-wrap gap-2 border-b border-slate-200 p-3"><SearchInput value={search} onChange={setSearch} onClear={()=>{setSearch('');apply({search:''});}} placeholder="Search conversations" className="min-w-52 flex-1" /><Select value={filters.team||''} onChange={(e)=>apply({team:e.target.value})} className="w-40"><option value="">All teams</option>{teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select value={filters.channel||''} onChange={(e)=>apply({channel:e.target.value})} className="w-40"><option value="">All channels</option>{channels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></div>{conversations.data.length?<div className="divide-y divide-slate-100">{conversations.data.map(c=><Link key={c.public_uuid} href={route('tenant.admin.inbox.show',c.public_uuid)} className="grid gap-2 p-4 hover:bg-slate-50 sm:grid-cols-[auto,1fr,auto]"><Avatar name={c.contact.display_name} size="sm" /><div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate font-semibold text-slate-900">{c.contact.display_name}</span>{c.unread_count>0&&<span className="h-2 w-2 rounded-full bg-brand-600" />}<Badge tone={priorityTone[c.priority]}>{c.priority}</Badge></div><p className="mt-1 truncate text-sm text-slate-500">{c.latest_message?.body||c.subject||'No message preview'}</p><div className="mt-2 flex flex-wrap gap-1">{c.tags.map(tag=><Badge key={tag.public_uuid}>{tag.name}</Badge>)}</div></div><div className="text-right text-xs text-slate-500"><p className="capitalize">{c.channel.type.replaceAll('_',' ')}</p><p className="mt-1">{c.assignee?.name||c.team?.name||'Unassigned'}</p><p className="mt-1">{c.last_message_at?new Date(c.last_message_at).toLocaleString():''}</p></div></Link>)}</div>:<EmptyState icon={Inbox} title="No conversations here" description="New customer messages will appear in this view." className="m-6" />}<div className="p-4"><Pagination links={conversations.links} /></div></section></div></AuthenticatedLayout>;
}
