import Pagination from '@/Components/Superadmin/Pagination';
import CustomersShell from '@/Components/Tenant/Customers/CustomersShell';
import Badge from '@/Components/UI/Badge';
import Button from '@/Components/UI/Button';
import { Head, useForm } from '@inertiajs/react';
import { Upload } from 'lucide-react';

export default function Index({ imports }) {
    const form = useForm({ file: null }); const submit = (e) => { e.preventDefault(); form.post(route('tenant.admin.customers.imports.store'), { forceFormData: true, preserveScroll: true, onSuccess: () => form.reset() }); };
    return <CustomersShell title="Contact imports" description="Queue validated CSV imports with duplicate matching and row-level failure reports."><Head title="Contact imports" /><form onSubmit={submit} className="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-5 shadow-soft sm:flex-row sm:items-end"><label className="flex-1 text-sm font-medium text-slate-700">CSV file<input type="file" accept=".csv,text/csv" onChange={(e) => form.setData('file', e.target.files[0])} className="mt-2 block w-full text-sm" /></label><Button type="submit" variant="brand" icon={Upload} loading={form.processing} disabled={!form.data.file}>Upload and queue</Button>{form.errors.file && <p className="text-xs text-rose-600">{form.errors.file}</p>}</form><div className="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-soft"><table className="min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">File</th><th className="px-4 py-3 text-left">Status</th><th className="px-4 py-3 text-left">Progress</th><th className="px-4 py-3 text-left">Result</th><th className="px-4 py-3 text-left">Started by</th></tr></thead><tbody className="divide-y divide-slate-100">{imports.data.map((item) => <tr key={item.public_uuid}><td className="px-4 py-3 font-medium">{item.original_filename}</td><td className="px-4 py-3"><Badge tone={item.status === 'failed' ? 'danger' : item.status.startsWith('completed') ? 'brand' : 'info'}>{item.status.replaceAll('_', ' ')}</Badge></td><td className="px-4 py-3">{item.processed_rows}/{item.total_rows || '?'}</td><td className="px-4 py-3 text-xs text-slate-600">{item.created_rows} created · {item.updated_rows} updated · {item.failed_rows} failed</td><td className="px-4 py-3">{item.creator?.name || 'System'}</td></tr>)}</tbody></table>{imports.data.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No imports have been run.</p>}</div><Pagination links={imports.links} /></CustomersShell>;
}
