<?php
namespace App\Http\Controllers\Tenant\Admin\Operations;
use App\Http\Controllers\Controller; use App\Models\BusinessHourPolicy; use App\Models\Operations\AgentPresence; use App\Models\Operations\AssignmentRule; use App\Models\Operations\SupportQueue; use App\Models\Sla\EscalationExecution; use App\Models\Sla\EscalationPolicy; use App\Models\Sla\SlaInstance; use App\Models\Sla\SlaPolicy; use App\Models\Team; use App\Models\User; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Str; use Illuminate\Validation\Rule; use Inertia\Inertia; use Inertia\Response;
class OperationsController extends Controller
{
 private function authorizeOperations(Request $r,string $permission='operations.view'):void{abort_unless($r->user('tenant')->can($permission),403);}
 public function index(Request $r):Response{$this->authorizeOperations($r);$users=User::where('status','active')->with(['presence','teams:id,name'])->orderBy('name')->get(['id','name','email']);return Inertia::render('Tenant/Admin/Operations/Index',['queues'=>SupportQueue::with('team:id,name')->orderBy('priority')->get(),'agents'=>$users->map(fn($u)=>array_merge($u->toArray(),['active_conversations'=>\App\Models\Inbox\Conversation::where('assignee_id',$u->id)->whereIn('status',['open','pending','waiting_on_customer'])->count(),'active_tickets'=>\App\Models\Ticket\Ticket::where('assignee_id',$u->id)->whereHas('status',fn($q)=>$q->whereNotIn('category',['resolved','closed']))->count()])),'rules'=>AssignmentRule::orderBy('resource_type')->orderBy('priority')->get(),'slaPolicies'=>SlaPolicy::with('businessHours:id,name')->orderBy('priority')->get(),'slaSummary'=>SlaInstance::selectRaw('state, count(*) total')->groupBy('state')->pluck('total','state'),'escalations'=>EscalationPolicy::orderBy('priority')->get(),'executions'=>EscalationExecution::with('policy:id,name')->latest('executed_at')->limit(50)->get(),'teams'=>Team::where('status','active')->orderBy('name')->get(['id','name']),'users'=>$users->map->only(['id','name']),'businessHours'=>BusinessHourPolicy::where('status','active')->orderBy('name')->get(['id','name'])]);}
 public function storeQueue(Request $r):RedirectResponse{$this->authorizeOperations($r,'operations.manage');$d=$r->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string','max:1000'],'team_id'=>['nullable','exists:teams,id'],'priority'=>['required','integer','min:0'],'assignment_method'=>['required','in:manual,round_robin,load_based'],'capacity'=>['nullable','integer','min:1'],'channel_scope'=>['nullable','array'],'conditions'=>['nullable','array']]);SupportQueue::create(array_merge($d,['active'=>true,'created_by'=>$r->user('tenant')->id]));return back()->with('status','Queue created.');}
 public function updatePresence(Request $r,User $user):RedirectResponse{$actor=$r->user('tenant');abort_unless($actor->id===$user->id||$actor->can('workforce.manage'),403);$d=$r->validate(['status'=>['required','in:online,away,busy,offline,on_break'],'conversation_capacity'=>['required','integer','min:0','max:1000'],'ticket_capacity'=>['required','integer','min:0','max:1000']]);AgentPresence::updateOrCreate(['user_id'=>$user->id],array_merge($d,['last_seen_at'=>now(),'status_changed_at'=>now()]));return back()->with('status','Agent availability updated.');}
 public function storeRule(Request $r):RedirectResponse{$this->authorizeOperations($r,'operations.manage');$d=$r->validate(['name'=>['required','string','max:255'],'resource_type'=>['required','in:conversation,ticket'],'priority'=>['required','integer','min:0'],'field'=>['required','string','max:100'],'operator'=>['required','in:equals,not_equals,in,contains'],'value'=>['nullable'],'action_type'=>['required','in:assign_team,assign_user,set_priority,assign_queue'],'action_value'=>['required']]);AssignmentRule::create(['name'=>$d['name'],'resource_type'=>$d['resource_type'],'priority'=>$d['priority'],'active'=>true,'conditions'=>['operator'=>'and','rules'=>[['field'=>$d['field'],'operator'=>$d['operator'],'value'=>$d['value']]]],'actions'=>[['type'=>$d['action_type'],$this->actionKey($d['action_type'])=>$d['action_value']]],'stop_processing'=>true,'created_by'=>$r->user('tenant')->id]);return back()->with('status','Assignment rule created.');}
 public function storeSla(Request $r):RedirectResponse{$this->authorizeOperations($r,'sla.manage');$d=$r->validate(['name'=>['required','string','max:255'],'calendar_mode'=>['required','in:24_7,business_hours'],'business_hours_policy_id'=>['nullable','exists:business_hour_policies,id'],'approaching_percentage'=>['required','integer','min:1','max:99'],'pause_statuses'=>['nullable','array'],'targets'=>['required','array'],'targets.*.first_response'=>['required','integer','min:1'],'targets.*.next_response'=>['nullable','integer','min:1'],'targets.*.resolution'=>['required','integer','min:1']]);SlaPolicy::create(array_merge($d,['active'=>true,'priority'=>SlaPolicy::max('priority')+10,'created_by'=>$r->user('tenant')->id]));return back()->with('status','SLA policy created.');}
 public function storeEscalation(Request $r):RedirectResponse{$this->authorizeOperations($r,'sla.manage');$d=$r->validate(['name'=>['required','string','max:255'],'sla_state'=>['required','in:approaching,breached'],'action_type'=>['required','in:set_priority,assign_team,assign_user,notify_user'],'action_value'=>['required'],'cooldown_minutes'=>['required','integer','min:1']]);EscalationPolicy::create(['name'=>$d['name'],'active'=>true,'priority'=>EscalationPolicy::max('priority')+10,'conditions'=>['operator'=>'and','rules'=>[['field'=>'sla.state','operator'=>'equals','value'=>$d['sla_state']]]],'actions'=>[['type'=>$d['action_type'],$this->actionKey($d['action_type'])=>$d['action_value']]],'cooldown_minutes'=>$d['cooldown_minutes'],'created_by'=>$r->user('tenant')->id]);return back()->with('status','Escalation policy created.');}
 private function actionKey(string $type):string{return match($type){'assign_team'=>'team_id','assign_user','notify_user'=>'user_id','assign_queue'=>'queue_id',default=>'priority'};}
}
