import Panel from '@/Components/Portal/Panel';
import StatusPill from '@/Components/Portal/StatusPill';
import UsageMetrics from '@/Components/UsageMetrics';
import PortalLayout from '@/Layouts/PortalLayout';
import { Link, router } from '@inertiajs/react';

export default function Show({ workspace, usage, members = [], capabilities = {} }) {
    const subscription = workspace.subscriptions?.[0];
    const domain = workspace.domains?.find(item => item.is_primary) || workspace.domains?.[0];
    return <PortalLayout title={workspace.company_name} actions={<div className="flex flex-wrap gap-2">{domain && <a href={`//${domain.domain}`} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Open PromptBot</a>}{workspace.last_provisioning_error && capabilities.retryProvisioning && <button onClick={() => router.post(route('portal.workspaces.retry', workspace.public_uuid), {}, { preserveScroll: true })} className="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white">Retry setup</button>}{capabilities.billing && <Link href={route('portal.billing.subscriptions', { workspace: workspace.id })} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Manage subscription</Link>}</div>}>
        <div className="grid gap-6 lg:grid-cols-3"><Panel title="Overview" className="lg:col-span-2"><dl className="grid gap-5 sm:grid-cols-2">{[['Status', <StatusPill value={workspace.status} />], ['Workspace ID', workspace.public_uuid], ['Plan', subscription?.plan?.name || workspace.plan?.name || 'None'], ['Subdomain', domain?.domain || workspace.slug], ['Created', new Date(workspace.created_at).toLocaleString()], ['Current billing period', subscription?.current_period_ends_at ? `Through ${new Date(subscription.current_period_ends_at).toLocaleDateString()}` : 'Not started']].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-all text-sm font-medium text-slate-900">{value}</dd></div>)}</dl></Panel><Panel title="Subscription"><div className="flex items-center justify-between"><span className="font-semibold text-slate-900">{subscription?.plan?.name || 'No subscription'}</span><StatusPill value={subscription?.status || 'pending'} /></div><p className="mt-3 text-sm capitalize text-slate-500">{subscription?.billing_interval || 'No billing interval'}</p>{subscription?.current_period_ends_at && <p className="mt-2 text-xs text-slate-500">Renews {new Date(subscription.current_period_ends_at).toLocaleDateString()}</p>}{capabilities.billing && <Link href={route('portal.billing.subscriptions', { workspace: workspace.id })} className="mt-5 inline-block text-sm font-semibold text-indigo-700">Change plan or billing cycle</Link>}</Panel></div>
        <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Usage" description="Current counters and plan limits for this workspace."><UsageMetrics usage={usage} compact /></Panel><Panel title="Domain"><div className="space-y-3">{workspace.domains?.length ? workspace.domains.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{item.domain}</span>{item.is_primary && <span className="text-xs font-semibold text-emerald-700">Primary</span>}</div>) : <p className="py-6 text-center text-sm text-slate-500">No domain is assigned while provisioning is incomplete.</p>}</div></Panel></div>
        <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Members" description="Account members who can access this workspace."><div className="divide-y">{members.map(member => <div key={member.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-semibold">{member.name}</p><p className="text-xs text-slate-500">{member.email}</p></div><span className="text-xs font-semibold capitalize text-slate-600">{member.pivot?.role}</span></div>)}</div><Link href={route('portal.members.index')} className="mt-4 inline-block text-sm font-semibold text-indigo-700">Manage account access</Link></Panel><Panel title="Billing"><dl className="space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Plan</dt><dd className="font-semibold">{subscription?.plan?.name || 'None'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Interval</dt><dd className="capitalize">{subscription?.billing_interval || '—'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Status</dt><dd><StatusPill value={subscription?.status || 'pending'} /></dd></div></dl>{capabilities.billing && <Link href={route('portal.billing.overview')} className="mt-5 inline-block text-sm font-semibold text-indigo-700">Open account billing</Link>}</Panel></div>
        <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Provisioning progress">{workspace.last_provisioning_error && <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong className="block">We’re having trouble finishing your workspace setup.</strong><span>Your account and billing information are safe. The platform has retained the setup state for a safe retry.</span></div>}{workspace.provisioning_logs?.length ? <div className="space-y-3">{workspace.provisioning_logs.map(log => <div key={log.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="capitalize text-slate-700">{log.step.replaceAll('_', ' ')}</span><StatusPill value={log.status} /></div>)}</div> : <p className="py-6 text-center text-sm text-slate-500">Provisioning has not started.</p>}</Panel><Panel title="Danger zone" description="Workspace data is never deleted immediately from the customer portal."><p className="text-sm text-slate-600">To stop service, schedule cancellation from subscription management. For ownership, domain, or urgent access changes, contact platform support.</p><div className="mt-5 flex flex-wrap gap-3">{capabilities.billing && <Link href={route('portal.billing.subscriptions', { workspace: workspace.id })} className="text-sm font-semibold text-rose-700">Manage cancellation</Link>}{capabilities.support && <Link href={route('portal.support.create', { workspace: workspace.id })} className="text-sm font-semibold text-indigo-700">Contact support</Link>}</div></Panel></div>
    </PortalLayout>;
}
