<?php
namespace App\Services\Automation;
use App\Models\Automation\AutomationLog; use App\Models\Automation\AutomationRule; use App\Models\Customer\Tag; use App\Models\Inbox\Conversation; use App\Models\Task\Task; use App\Models\Ticket\Ticket; use Illuminate\Database\Eloquent\Model; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Throwable;
class AutomationExecutionService
{
 public function __construct(private readonly ConditionEvaluator $conditions){}
 public function dispatch(string $trigger,Model $resource):int{$type=$resource instanceof Conversation?'conversation':($resource instanceof Ticket?'ticket':null);if(!$type)return 0;$count=0;$context=$this->context($resource,$type);foreach(AutomationRule::where('trigger',$trigger)->where('resource_type',$type)->where('active',true)->orderBy('priority')->limit(20)->get() as $rule){if(!$this->conditions->matches($rule->conditions??[],$context))continue;$this->execute($rule,$trigger,$type,$resource);$count++;}return $count;}
 private function execute(AutomationRule $rule,string $trigger,string $type,Model $resource):void{$log=AutomationLog::create(['automation_rule_id'=>$rule->id,'trigger'=>$trigger,'resource_type'=>$type,'resource_id'=>$resource->id,'execution_key'=>(string)Str::uuid(),'status'=>'running','condition_result'=>['matched'=>true],'started_at'=>now()]);$done=[];try{DB::transaction(function()use($rule,$resource,$type,&$done):void{foreach(array_slice($rule->actions??[],0,20) as $action){$this->action($resource,$type,$action);$done[]=$action;}});$log->update(['status'=>'completed','actions_executed'=>$done,'finished_at'=>now()]);$rule->update(['run_count'=>DB::raw('run_count + 1'),'last_run_at'=>now(),'last_error'=>null]);}catch(Throwable $e){report($e);$log->update(['status'=>'failed','actions_executed'=>$done,'error_message'=>$e->getMessage(),'finished_at'=>now()]);$rule->update(['last_error_at'=>now(),'last_error'=>$e->getMessage()]);}}
 private function action(Model $r,string $type,array $a):void{match($a['type']??null){'set_priority'=>$r->update(['priority'=>$a['value']??'normal']),'assign_user'=>$r->update(['assignee_id'=>$a['value']??null]),'assign_team'=>$r->update(['team_id'=>$a['value']??null]),'set_status'=>$this->status($r,$type,$a['value']??null),'add_tag'=>$this->tag($r,$a['value']??null),'create_task'=>Task::create(['title'=>$a['value']??'Automated follow-up','status'=>'todo','priority'=>'normal','related_type'=>$type,'related_id'=>$r->id]),default=>null};}
 private function status(Model $r,string $type,$value):void{if($type==='conversation')$r->update(['status'=>$value]);else $r->update(['status_id'=>$value]);} private function tag(Model $r,$value):void{$tag=is_numeric($value)?Tag::find($value):Tag::where('name',$value)->first();if($tag&&method_exists($r,'tags'))$r->tags()->syncWithoutDetaching([$tag->id]);}
 private function context(Model $r,string $type):array{return['resource'=>['type'=>$type,'priority'=>$r->priority,'status'=>$type==='ticket'?$r->status?->category:$r->status,'team_id'=>$r->team_id,'assignee_id'=>$r->assignee_id,'channel_id'=>$r->channel_id],'customer'=>['status'=>$r->contact?->status,'language'=>$r->contact?->preferred_language,'company_id'=>$r->company_id],'channel'=>['type'=>$r->channel?->type],'time'=>['hour'=>now()->hour,'weekday'=>now()->dayOfWeek]];}
}
