import Pagination from '@/Components/Superadmin/Pagination';
import CustomersShell from '@/Components/Tenant/Customers/CustomersShell';
import Button from '@/Components/UI/Button';
import FormField from '@/Components/UI/FormField';
import Input from '@/Components/UI/Input';
import { Head, useForm } from '@inertiajs/react';
import { Plus, Tags } from 'lucide-react';

export default function Index({ tags }) {
    const form = useForm({ name: '', color: '#64748b', description: '' });
    const submit = (e) => { e.preventDefault(); form.post(route('tenant.admin.customers.tags.store'), { preserveScroll: true, onSuccess: () => form.reset('name', 'description') }); };
    return <CustomersShell title="Tags" description="Reusable, controlled labels for customer and support resources."><Head title="Customer tags" /><div className="grid gap-5 lg:grid-cols-[360px,1fr]"><form onSubmit={submit} className="h-fit space-y-4 rounded-lg border border-slate-200 bg-white p-5 shadow-soft"><h2 className="flex items-center gap-2 text-sm font-semibold"><Plus className="h-4 w-4" />Create tag</h2><FormField label="Name" required error={form.errors.name}><Input value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} /></FormField><FormField label="Color" error={form.errors.color}><Input type="color" value={form.data.color} onChange={(e) => form.setData('color', e.target.value)} className="h-10 p-1" /></FormField><FormField label="Description"><Input value={form.data.description} onChange={(e) => form.setData('description', e.target.value)} /></FormField><Button type="submit" variant="brand" loading={form.processing}>Create tag</Button></form><div>{tags.data.length ? <div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-soft"><table className="min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">Tag</th><th className="px-4 py-3 text-left">Usage</th><th className="px-4 py-3 text-left">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{tags.data.map((tag) => <tr key={tag.public_uuid}><td className="px-4 py-3"><span className="mr-2 inline-block h-3 w-3 rounded-full" style={{ backgroundColor: tag.color }} /><span className="font-medium">{tag.name}</span><p className="text-xs text-slate-500">{tag.description}</p></td><td className="px-4 py-3 text-slate-600">{tag.contacts_count} contacts · {tag.companies_count} companies</td><td className="px-4 py-3 capitalize text-slate-600">{tag.status}</td></tr>)}</tbody></table></div> : <div className="rounded-lg border border-dashed p-12 text-center"><Tags className="mx-auto h-7 w-7 text-slate-400" /><p className="mt-2 text-sm text-slate-500">No tags yet.</p></div>}<Pagination links={tags.links} /></div></div></CustomersShell>;
}
