import Badge from '@/Components/UI/Badge';
import Button from '@/Components/UI/Button';
import FormField from '@/Components/UI/FormField';
import Input from '@/Components/UI/Input';
import Select from '@/Components/UI/Select';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';

export default function Settings({ statuses, categories }) {
    const status = useForm({ name: '', category: 'open', color: '#2563eb' });
    const category = useForm({ name: '', parent_id: '', description: '' });
    return <AuthenticatedLayout title="Tickets" header={<div><h1 className="text-xl font-bold">Ticket configuration</h1><p className="text-sm text-slate-500">Customize labels while preserving stable workflow categories.</p></div>}><Head title="Ticket configuration" /><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-lg border bg-white p-5"><h2 className="font-semibold">Statuses</h2><form onSubmit={e => { e.preventDefault(); status.post(route('tenant.admin.tickets.settings.statuses.store'), { onSuccess: () => status.reset('name') }); }} className="mt-4 grid gap-3 sm:grid-cols-2"><FormField label="Label"><Input value={status.data.name} onChange={e => status.setData('name', e.target.value)} /></FormField><FormField label="System category"><Select value={status.data.category} onChange={e => status.setData('category', e.target.value)}>{['new', 'open', 'pending', 'waiting_on_customer', 'resolved', 'closed'].map(x => <option key={x} value={x}>{x.replaceAll('_', ' ')}</option>)}</Select></FormField><FormField label="Color"><Input type="color" value={status.data.color} onChange={e => status.setData('color', e.target.value)} className="h-10 p-1" /></FormField><div className="self-end"><Button type="submit" variant="brand">Add status</Button></div></form><div className="mt-5 divide-y">{statuses.map(x => <div key={x.public_uuid} className="flex items-center justify-between py-3"><span><span className="font-medium">{x.name}</span><span className="ml-2 text-xs text-slate-500">{x.category.replaceAll('_', ' ')}</span></span><span className="flex items-center gap-2"><Badge tone={x.active ? 'brand' : 'neutral'}>{x.active ? 'Active' : 'Archived'}</Badge><span className="text-xs text-slate-500">{x.tickets_count} tickets</span></span></div>)}</div></section><section className="rounded-lg border bg-white p-5"><h2 className="font-semibold">Categories</h2><form onSubmit={e => { e.preventDefault(); category.post(route('tenant.admin.tickets.settings.categories.store'), { onSuccess: () => category.reset() }); }} className="mt-4 space-y-3"><FormField label="Name"><Input value={category.data.name} onChange={e => category.setData('name', e.target.value)} /></FormField><FormField label="Parent"><Select value={category.data.parent_id} onChange={e => category.setData('parent_id', e.target.value)}><option value="">Top level</option>{categories.filter(x => !x.parent_id).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormField><Button type="submit" variant="brand">Add category</Button></form><div className="mt-5 divide-y">{categories.map(x => <div key={x.public_uuid} className="flex justify-between py-3"><span>{x.parent ? `${x.parent.name} / ` : ''}<span className="font-medium">{x.name}</span></span><span className="text-xs text-slate-500">{x.tickets_count} tickets</span></div>)}</div></section></div></AuthenticatedLayout>;
}
