import Badge from '@/Components/UI/Badge';
import Button from '@/Components/UI/Button';
import { Card, SectionCard } from '@/Components/UI/Card';
import Select from '@/Components/UI/Select';
import Textarea from '@/Components/UI/Textarea';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { Merge, Pencil, Plus, Sparkles, Trash2 } from 'lucide-react';

export default function Show({ ticket, users, teams, statuses, mergeCandidates, aiSuggestions = [] }) {
    const permissions = usePage().props.auth?.permissions || [];
    const comment = useForm({ body: '', internal: true });
    const merge = useForm({ destination_id: '', reason: '' });
    const latestAI = aiSuggestions.find((item) => item.status === 'generated') || aiSuggestions[0];
    const runAI = (operation) => router.post(route('tenant.admin.tickets.ai.run', ticket.public_uuid), { operation }, { preserveScroll: true });
    const add = (event) => { event.preventDefault(); comment.post(route('tenant.admin.tickets.comments.store', ticket.public_uuid), { preserveScroll: true, onSuccess: () => comment.reset('body') }); };
    const update = (key, value) => router.put(route('tenant.admin.tickets.update', ticket.public_uuid), { ...ticket, [key]: value, tag_ids: ticket.tags.map((tag) => tag.id), custom_fields: Object.fromEntries(ticket.custom_field_values.map((field) => [field.field.key, field.value])) }, { preserveScroll: true });

    return <AuthenticatedLayout title="Tickets" header={<div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-xl font-bold">{ticket.ticket_number}</h1><Badge tone="info">{ticket.status.name}</Badge></div><p className="mt-1 text-sm text-slate-600">{ticket.subject}</p></div><div className="flex gap-2">{permissions.includes('tickets.update') && <Button href={route('tenant.admin.tickets.edit', ticket.public_uuid)} variant="secondary" icon={Pencil}>Edit</Button>}{permissions.includes('tasks.create') && <Button href={route('tenant.admin.tasks.create', { related_type: 'ticket', related_id: ticket.id })} variant="secondary" icon={Plus}>Task</Button>}{permissions.includes('tickets.delete') && <Button variant="danger" icon={Trash2} onClick={() => window.confirm('Archive this ticket?') && router.delete(route('tenant.admin.tickets.destroy', ticket.public_uuid))}>Archive</Button>}</div></div>}>
        <Head title={ticket.ticket_number} />
        <div className="grid gap-5 xl:grid-cols-[1fr,320px]">
            <main className="space-y-5">
                <SectionCard title="Description"><p className="whitespace-pre-wrap text-sm text-slate-700">{ticket.description || 'No description.'}</p></SectionCard>
                <SectionCard title="Comments"><div className="space-y-3">{ticket.comments.map((entry) => <article key={entry.public_uuid} className={`rounded-lg p-3 ${entry.internal ? 'border border-amber-200 bg-amber-50' : 'bg-slate-50'}`}><p className="whitespace-pre-wrap text-sm">{entry.body}</p><p className="mt-2 text-xs text-slate-500">{entry.user?.name || entry.author_name || 'System'} · {new Date(entry.created_at).toLocaleString()} · {entry.internal ? 'Internal' : 'Public'}</p></article>)}</div>{permissions.includes('tickets.update') && <form onSubmit={add} className="mt-4"><Textarea value={comment.data.body} onChange={(event) => comment.setData('body', event.target.value)} placeholder="Add a ticket comment…" /><label className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={comment.data.internal} onChange={(event) => comment.setData('internal', event.target.checked)} />Internal comment</label><Button type="submit" variant="brand" size="sm" className="mt-2" loading={comment.processing}>Add comment</Button></form>}</SectionCard>
                <SectionCard title="Activity"><ol className="space-y-4">{ticket.activities.map((activity) => <li key={activity.public_uuid} className="border-l-2 border-slate-200 pl-4"><p className="text-sm font-medium">{activity.description}</p><p className="text-xs text-slate-500">{activity.actor?.name || activity.actor_name || 'System'} · {new Date(activity.occurred_at).toLocaleString()}</p></li>)}</ol></SectionCard>
            </main>
            <aside className="space-y-5">
                {permissions.includes('ai.copilot.use') && <Card><h2 className="flex items-center gap-2 text-xs font-bold uppercase text-brand-700"><Sparkles className="h-4 w-4" />Ticket AI</h2><p className="mt-1 text-xs text-slate-500">Suggestions only; never applied automatically.</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => runAI('summary')}>Summary</Button><Button size="sm" onClick={() => runAI('draft')}>Draft</Button><Button size="sm" variant="secondary" onClick={() => runAI('action_items')}>Action items</Button></div>{latestAI && <div className="mt-3 rounded bg-slate-50 p-3"><Badge>{latestAI.type}</Badge><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{latestAI.text}</p>{latestAI.type === 'draft' && <Button className="mt-3" size="sm" onClick={() => comment.setData('body', latestAI.text)}>Use in comment</Button>}</div>}</Card>}
                <Card><h2 className="text-xs font-bold uppercase text-slate-400">Details</h2><div className="mt-3 space-y-3"><label className="block text-xs">Status<Select className="mt-1" value={ticket.status_id} onChange={(event) => update('status_id', event.target.value)}>{statuses.map((status) => <option key={status.id} value={status.id}>{status.name}</option>)}</Select></label><label className="block text-xs">Priority<Select className="mt-1" value={ticket.priority} onChange={(event) => update('priority', event.target.value)}>{['low','normal','high','urgent'].map((priority) => <option key={priority}>{priority}</option>)}</Select></label><label className="block text-xs">Team<Select className="mt-1" value={ticket.team_id || ''} onChange={(event) => update('team_id', event.target.value || null)}><option value="">None</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</Select></label><label className="block text-xs">Assignee<Select className="mt-1" value={ticket.assignee_id || ''} onChange={(event) => update('assignee_id', event.target.value || null)}><option value="">Unassigned</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</Select></label></div></Card>
                <Card><h2 className="text-xs font-bold uppercase text-slate-400">Customer</h2><Link href={route('tenant.admin.customers.contacts.show', ticket.contact.public_uuid)} className="mt-2 block font-semibold text-brand-700">{ticket.contact.display_name}</Link><p className="text-sm text-slate-500">{ticket.contact.email}</p>{ticket.conversation && <Link href={route('tenant.admin.inbox.show', ticket.conversation.public_uuid)} className="mt-3 block text-sm text-brand-700">Open linked conversation</Link>}</Card>
                {permissions.includes('tickets.merge') && <Card><h2 className="flex items-center gap-2 text-xs font-bold uppercase text-slate-400"><Merge className="h-4 w-4" />Merge duplicate</h2><form onSubmit={(event) => { event.preventDefault(); merge.post(route('tenant.admin.tickets.merge', ticket.public_uuid)); }} className="mt-3 space-y-2"><Select value={merge.data.destination_id} onChange={(event) => merge.setData('destination_id', event.target.value)}><option value="">Destination ticket</option>{mergeCandidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.ticket_number} — {candidate.subject}</option>)}</Select><Textarea rows={2} value={merge.data.reason} onChange={(event) => merge.setData('reason', event.target.value)} placeholder="Reason" /><Button type="submit" variant="danger" size="sm" disabled={!merge.data.destination_id}>Merge ticket</Button></form></Card>}
            </aside>
        </div>
    </AuthenticatedLayout>;
}
