import ApplicationLogo from '@/Components/ApplicationLogo';
import Money from '@/Components/Portal/Money';
import GuestLayout from '@/Layouts/GuestLayout';
import { Head, Link, useForm } from '@inertiajs/react';

export default function Register({ selectedPlan, interval }) {
    const {data,setData,post,processing,errors}=useForm({name:'',email:'',password:'',password_confirmation:'',account_name:'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,plan:selectedPlan?.slug||'',interval});
    const submit=(e)=>{e.preventDefault();post(route('portal.register.store'))}; const cls='mt-1.5 w-full rounded-lg border-slate-300';
    return <GuestLayout wide><Head title="Create customer account" /><div className="grid overflow-hidden rounded-xl border border-slate-200 bg-white shadow-lg lg:grid-cols-[1fr_0.8fr]"><form onSubmit={submit} className="p-7 sm:p-10"><div className="flex items-center gap-3"><ApplicationLogo className="h-9 w-9" /><div><h1 className="text-2xl font-bold text-slate-950">Create your PromptBot account</h1><p className="text-sm text-slate-500">One login for every workspace you own.</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Your name<input className={cls} value={data.name} onChange={(e)=>setData('name',e.target.value)} required />{errors.name&&<span className="text-xs text-rose-600">{errors.name}</span>}</label><label className="text-sm font-medium">Work email<input type="email" className={cls} value={data.email} onChange={(e)=>setData('email',e.target.value)} required />{errors.email&&<span className="text-xs text-rose-600">{errors.email}</span>}</label><label className="text-sm font-medium sm:col-span-2">Company or account name<input className={cls} value={data.account_name} onChange={(e)=>setData('account_name',e.target.value)} required />{errors.account_name&&<span className="text-xs text-rose-600">{errors.account_name}</span>}</label><label className="text-sm font-medium">Password<input type="password" className={cls} value={data.password} onChange={(e)=>setData('password',e.target.value)} required />{errors.password&&<span className="text-xs text-rose-600">{errors.password}</span>}</label><label className="text-sm font-medium">Confirm password<input type="password" className={cls} value={data.password_confirmation} onChange={(e)=>setData('password_confirmation',e.target.value)} required /></label></div><button disabled={processing} className="mt-6 w-full rounded-lg bg-indigo-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{processing?'Creating account…':'Create account and continue'}</button><p className="mt-5 text-center text-sm text-slate-500">Already a customer? <Link href={route('portal.login')} className="font-semibold text-indigo-600">Sign in</Link></p></form><aside className="bg-slate-950 p-8 text-white sm:p-10"><p className="text-sm font-semibold text-indigo-300">Selected plan</p>{selectedPlan?<><h2 className="mt-3 text-2xl font-bold">{selectedPlan.name}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{selectedPlan.description}</p><p className="mt-6 text-3xl font-bold"><Money value={interval==='yearly'?selectedPlan.annual_price:selectedPlan.monthly_price} currency={selectedPlan.currency} /><span className="text-sm font-normal text-slate-400">/{interval==='yearly'?'year':'month'}</span></p></>:<><h2 className="mt-3 text-2xl font-bold">Choose after registration</h2><p className="mt-2 text-sm leading-6 text-slate-300">You will select a public plan before provisioning your first workspace.</p></>}</aside></div></GuestLayout>;
}
