<?php
namespace App\Http\Controllers\Tenant\Admin\Experience;
use App\Http\Controllers\Controller;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Inertia\Inertia;use Inertia\Response;
class ExperienceController extends Controller
{
 private function access(Request $r,string $permission='experience.view'):void{abort_unless($r->user('tenant')->can($permission),403);}
 public function index(Request $r):Response{$this->access($r);return Inertia::render('Tenant/Admin/Experience/Index',['segments'=>DB::table('contact_segments')->latest()->get(),'lists'=>DB::table('contact_lists')->latest()->get(),'forms'=>DB::table('support_forms')->latest()->get(),'submissions'=>DB::table('support_form_submissions')->latest('submitted_at')->limit(50)->get(),'helpCenter'=>DB::table('help_center_settings')->first(),'surveys'=>DB::table('csat_surveys')->latest()->get(),'responses'=>DB::table('csat_responses')->latest('submitted_at')->limit(100)->get(),'csat'=>['average'=>(float)(DB::table('csat_responses')->avg('rating')??0),'responses'=>DB::table('csat_responses')->count()]]);}
 public function storeSegment(Request $r):RedirectResponse{$this->access($r,'experience.manage');$d=$r->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string'],'field'=>['required','in:status,preferred_language,country,company_id'],'operator'=>['required','in:equals,not_equals,contains'],'value'=>['required']]);DB::table('contact_segments')->insert(['public_uuid'=>(string)Str::uuid(),'name'=>$d['name'],'description'=>$d['description']??null,'conditions'=>json_encode(['operator'=>'and','rules'=>[['field'=>$d['field'],'operator'=>$d['operator'],'value'=>$d['value']]]]),'active'=>true,'created_by'=>$r->user('tenant')->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','Dynamic segment created.');}
 public function storeList(Request $r):RedirectResponse{$this->access($r,'experience.manage');$d=$r->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string']]);DB::table('contact_lists')->insert(['public_uuid'=>(string)Str::uuid(),'name'=>$d['name'],'description'=>$d['description']??null,'active'=>true,'created_by'=>$r->user('tenant')->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','Contact list created.');}
 public function storeForm(Request $r):RedirectResponse{$this->access($r,'experience.manage');$d=$r->validate(['name'=>['required','string','max:255'],'slug'=>['required','alpha_dash','max:100','unique:support_forms,slug'],'description'=>['nullable','string']]);$id=DB::table('support_forms')->insertGetId(['public_uuid'=>(string)Str::uuid(),'name'=>$d['name'],'slug'=>$d['slug'],'description'=>$d['description']??null,'active'=>true,'settings'=>json_encode(['success_message'=>'Thanks. Your request has been received.']),'created_by'=>$r->user('tenant')->id,'created_at'=>now(),'updated_at'=>now()]);DB::table('support_form_fields')->insert([['support_form_id'=>$id,'key'=>'email','label'=>'Email','type'=>'email','required'=>true,'display_order'=>10],['support_form_id'=>$id,'key'=>'subject','label'=>'Subject','type'=>'text','required'=>true,'display_order'=>20],['support_form_id'=>$id,'key'=>'message','label'=>'How can we help?','type'=>'textarea','required'=>true,'display_order'=>30]]);return back()->with('status','Support form created.');}
 public function updateHelpCenter(Request $r):RedirectResponse{$this->access($r,'experience.manage');$d=$r->validate(['name'=>['required','string','max:255'],'slug'=>['required','alpha_dash','max:100'],'welcome_text'=>['nullable','string','max:2000'],'primary_color'=>['required','regex:/^#[0-9a-fA-F]{6}$/'],'active'=>['required','boolean'],'allow_ticket_submission'=>['required','boolean'],'allow_portal'=>['required','boolean']]);DB::table('help_center_settings')->updateOrInsert(['id'=>1],array_merge($d,['updated_at'=>now(),'created_at'=>now()]));return back()->with('status','Help center settings saved.');}
 public function storeSurvey(Request $r):RedirectResponse{$this->access($r,'experience.manage');$d=$r->validate(['name'=>['required','string','max:255'],'question'=>['required','string','max:500'],'resource_type'=>['required','in:conversation,ticket'],'scale'=>['required','integer','in:3,5,10']]);DB::table('csat_surveys')->insert(array_merge($d,['public_uuid'=>(string)Str::uuid(),'active'=>true,'created_at'=>now(),'updated_at'=>now()]));return back()->with('status','CSAT survey created.');}
 public function portalLink(Request $r):RedirectResponse{$this->access($r,'experience.manage');$d=$r->validate(['contact_id'=>['required','exists:contacts,id']]);$plain=Str::random(64);DB::table('customer_portal_tokens')->where('contact_id',$d['contact_id'])->whereNull('revoked_at')->update(['revoked_at'=>now(),'updated_at'=>now()]);DB::table('customer_portal_tokens')->insert(['public_uuid'=>(string)Str::uuid(),'contact_id'=>$d['contact_id'],'token_hash'=>hash('sha256',$plain),'expires_at'=>now()->addDays(7),'created_at'=>now(),'updated_at'=>now()]);return back()->with('portal_url',route('tenant.portal',$plain))->with('status','A seven-day customer portal link was generated.');}
}
