import Button from '@/Components/UI/Button';
import FormField from '@/Components/UI/FormField';
import Input from '@/Components/UI/Input';
import Select from '@/Components/UI/Select';
import Textarea from '@/Components/UI/Textarea';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';

export default function Form({ channel, selectedType, catalog, teams, users, businessHours, hasCredentials }) {
    const editing = !!channel; const email = channel?.email_settings || {}; const widget = channel?.web_chat_widget || {};
    const form = useForm({ type: channel?.type || selectedType, name: channel?.name || '', status: channel?.status || 'draft', team_id: channel?.team_id || '', default_assignee_id: channel?.default_assignee_id || '', business_hours_policy_id: channel?.business_hours_policy_id || '', auto_reply_enabled: channel?.auto_reply_enabled || false, signature: channel?.signature || '', email: { inbox_address: email.inbox_address || '', incoming_provider: email.incoming_provider || 'webhook', outgoing_provider: email.outgoing_provider || 'laravel_mail', from_name: email.from_name || '', reply_to_address: email.reply_to_address || '' }, credentials: { host: '', port: 587, username: '', password: '', encryption: 'tls' }, widget: { widget_name: widget.widget_name || '', primary_color: widget.primary_color || '#2563eb', launcher_position: widget.launcher_position || 'right', welcome_message: widget.welcome_message || 'How can we help?', offline_message: widget.offline_message || 'We are currently offline. Leave a message and we will get back to you.', supported_languages: widget.supported_languages || ['en'], allowed_origins: widget.allowed_origins || [], privacy_url: widget.privacy_url || '', terms_url: widget.terms_url || '', allow_attachments: widget.allow_attachments ?? true, require_email: widget.require_email ?? true, require_name: widget.require_name ?? true } });
    const setNested = (group, key, value) => form.setData(group, { ...form.data[group], [key]: value });
    const submit = (e) => { e.preventDefault(); editing ? form.put(route('tenant.admin.channels.update', channel.public_uuid)) : form.post(route('tenant.admin.channels.store')); };
    const selected = catalog.find((x) => x.type === form.data.type);
    return <AuthenticatedLayout title="Channels" header={<div><h1 className="text-xl font-bold text-navy-900">{editing ? `Edit ${channel.name}` : 'Add channel'}</h1><p className="mt-1 text-sm text-slate-500">Credentials are encrypted and never returned to the browser after saving.</p></div>}><Head title={editing ? 'Edit channel' : 'Add channel'} /><form onSubmit={submit} className="mx-auto max-w-4xl space-y-5"><div className="grid gap-5 rounded-lg border border-slate-200 bg-white p-5 shadow-soft md:grid-cols-2"><FormField label="Channel type" required error={form.errors.type}><Select value={form.data.type} disabled={editing} onChange={(e) => form.setData('type', e.target.value)}>{catalog.map((x) => <option key={x.type} value={x.type}>{x.label}{x.available ? '' : ' — requires provider'}</option>)}</Select>{selected && !selected.available && <p className="mt-2 text-xs text-amber-700">This adapter is not installed and cannot be activated in this release.</p>}</FormField><FormField label="Name" required error={form.errors.name}><Input value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} /></FormField><FormField label="Status" error={form.errors.status}><Select value={form.data.status} onChange={(e) => form.setData('status', e.target.value)}><option value="draft">Draft</option><option value="active">Active</option><option value="disabled">Disabled</option></Select></FormField><FormField label="Team"><Select value={form.data.team_id} onChange={(e) => form.setData('team_id', e.target.value)}><option value="">No default team</option>{teams.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormField><FormField label="Default assignee"><Select value={form.data.default_assignee_id} onChange={(e) => form.setData('default_assignee_id', e.target.value)}><option value="">Unassigned</option>{users.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormField><FormField label="Business hours"><Select value={form.data.business_hours_policy_id} onChange={(e) => form.setData('business_hours_policy_id', e.target.value)}><option value="">Always available</option>{businessHours.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormField></div>
        {form.data.type === 'email' && <div className="grid gap-5 rounded-lg border border-slate-200 bg-white p-5 shadow-soft md:grid-cols-2"><h2 className="md:col-span-2 text-sm font-semibold">Email configuration</h2><FormField label="Inbox address" required error={form.errors['email.inbox_address']}><Input type="email" value={form.data.email.inbox_address} onChange={(e) => setNested('email', 'inbox_address', e.target.value)} /></FormField><FormField label="From name"><Input value={form.data.email.from_name} onChange={(e) => setNested('email', 'from_name', e.target.value)} /></FormField><FormField label="Incoming provider"><Select value={form.data.email.incoming_provider} onChange={(e) => setNested('email', 'incoming_provider', e.target.value)}><option value="webhook">Signed inbound webhook</option><option value="imap">IMAP (server extension required)</option></Select></FormField><FormField label="Outgoing provider"><Select value={form.data.email.outgoing_provider} onChange={(e) => setNested('email', 'outgoing_provider', e.target.value)}><option value="laravel_mail">Application mail configuration</option><option value="smtp">Channel-specific SMTP</option></Select></FormField><FormField label="Reply-to"><Input type="email" value={form.data.email.reply_to_address} onChange={(e) => setNested('email', 'reply_to_address', e.target.value)} /></FormField><FormField label="Signature"><Textarea value={form.data.signature} onChange={(e) => form.setData('signature', e.target.value)} /></FormField>{form.data.email.outgoing_provider === 'smtp' && <><p className="md:col-span-2 text-xs text-slate-500">{hasCredentials ? 'Leave secret fields blank to keep the current encrypted credentials.' : 'Enter the SMTP credentials for this channel.'}</p><FormField label="SMTP host"><Input value={form.data.credentials.host} onChange={(e) => setNested('credentials', 'host', e.target.value)} /></FormField><FormField label="Port"><Input type="number" value={form.data.credentials.port} onChange={(e) => setNested('credentials', 'port', e.target.value)} /></FormField><FormField label="Username"><Input autoComplete="off" value={form.data.credentials.username} onChange={(e) => setNested('credentials', 'username', e.target.value)} /></FormField><FormField label="Password"><Input type="password" autoComplete="new-password" value={form.data.credentials.password} onChange={(e) => setNested('credentials', 'password', e.target.value)} /></FormField></>}</div>}
        {form.data.type === 'web_chat' && <div className="grid gap-5 rounded-lg border border-slate-200 bg-white p-5 shadow-soft md:grid-cols-2"><h2 className="md:col-span-2 text-sm font-semibold">Widget configuration</h2><FormField label="Widget name" required><Input value={form.data.widget.widget_name} onChange={(e) => setNested('widget', 'widget_name', e.target.value)} /></FormField><FormField label="Brand color"><Input type="color" className="h-10 p-1" value={form.data.widget.primary_color} onChange={(e) => setNested('widget', 'primary_color', e.target.value)} /></FormField><FormField label="Launcher position"><Select value={form.data.widget.launcher_position} onChange={(e) => setNested('widget', 'launcher_position', e.target.value)}><option value="right">Right</option><option value="left">Left</option></Select></FormField><FormField label="Allowed origins" hint="Comma-separated website URLs"><Input value={form.data.widget.allowed_origins.join(', ')} onChange={(e) => setNested('widget', 'allowed_origins', e.target.value.split(',').map((x) => x.trim()).filter(Boolean))} /></FormField><FormField label="Welcome message" className="md:col-span-2"><Input value={form.data.widget.welcome_message} onChange={(e) => setNested('widget', 'welcome_message', e.target.value)} /></FormField><FormField label="Offline message" className="md:col-span-2"><Input value={form.data.widget.offline_message} onChange={(e) => setNested('widget', 'offline_message', e.target.value)} /></FormField>{[['require_name', 'Require name'], ['require_email', 'Require email'], ['allow_attachments', 'Allow attachments']].map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.widget[key]} onChange={(e) => setNested('widget', key, e.target.checked)} />{label}</label>)}</div>}
        <div className="flex justify-end gap-2"><Button href={route('tenant.admin.channels.index')} variant="secondary">Cancel</Button><Button type="submit" variant="brand" loading={form.processing} disabled={!selected?.available}>{editing ? 'Save channel' : 'Create channel'}</Button></div></form></AuthenticatedLayout>;
}
