import Pagination from '@/Components/Superadmin/Pagination';
import CustomersShell from '@/Components/Tenant/Customers/CustomersShell';
import Badge from '@/Components/UI/Badge';
import Button from '@/Components/UI/Button';
import { Card, SectionCard } from '@/Components/UI/Card';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { Archive, Globe, Pencil, Phone } from 'lucide-react';

export default function Show({ company, contacts }) {
    const permissions = usePage().props.auth?.permissions || [];
    const archive = () => window.confirm(`Archive ${company.name}? Contacts remain available and the company can be restored.`) && router.delete(route('tenant.admin.customers.companies.destroy', company.public_uuid));
    return <CustomersShell title={company.name} description="Company account, contacts, and support activity." actions={<>{permissions.includes('companies.update') && <Button href={route('tenant.admin.customers.companies.edit', company.public_uuid)} variant="secondary" icon={Pencil}>Edit</Button>}{permissions.includes('companies.delete') && <Button variant="danger" icon={Archive} onClick={archive}>Archive</Button>}</>}><Head title={company.name} /><div className="grid gap-5 xl:grid-cols-[340px,1fr]"><div className="space-y-5"><Card><Badge tone={company.status === 'active' ? 'brand' : 'neutral'}>{company.status}</Badge><dl className="mt-4 space-y-3 text-sm">{company.domain && <div className="flex gap-2"><Globe className="h-4 w-4 text-slate-400" />{company.domain}</div>}{company.phone && <div className="flex gap-2"><Phone className="h-4 w-4 text-slate-400" />{company.phone}</div>}<div><dt className="text-xs uppercase text-slate-400">Industry</dt><dd>{company.industry || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-400">Account owner</dt><dd>{company.account_owner?.name || 'Unassigned'}</dd></div></dl>{company.tags.length > 0 && <div className="mt-4 flex flex-wrap gap-1">{company.tags.map((tag) => <Badge key={tag.public_uuid}>{tag.name}</Badge>)}</div>}</Card>{company.notes && <SectionCard title="Notes"><p className="whitespace-pre-wrap text-sm text-slate-600">{company.notes}</p></SectionCard>}</div><div className="space-y-5"><SectionCard title={`Contacts (${contacts.total})`}>{contacts.data.length ? <div className="divide-y divide-slate-100">{contacts.data.map((contact) => <Link key={contact.public_uuid} href={route('tenant.admin.customers.contacts.show', contact.public_uuid)} className="flex items-center justify-between py-3 first:pt-0 last:pb-0"><span><span className="block text-sm font-medium text-slate-900">{contact.display_name}</span><span className="block text-xs text-slate-500">{contact.email || contact.phone || 'No contact point'}</span></span><span className="text-xs text-slate-500">{contact.owner?.name || 'Unassigned'}</span></Link>)}</div> : <p className="text-sm text-slate-500">No contacts belong to this company.</p>}<Pagination links={contacts.links} /></SectionCard><SectionCard title="Activity timeline">{company.activities.length ? <ol className="space-y-4">{company.activities.map((activity) => <li key={activity.public_uuid} className="border-l-2 border-brand-200 pl-4"><p className="text-sm font-medium text-slate-800">{activity.description}</p><p className="text-xs text-slate-500">{activity.actor?.name || activity.actor_name || 'System'} · {new Date(activity.occurred_at).toLocaleString()}</p></li>)}</ol> : <p className="text-sm text-slate-500">No company activity yet.</p>}</SectionCard></div></div></CustomersShell>;
}
