import CustomersShell from '@/Components/Tenant/Customers/CustomersShell';
import Button from '@/Components/UI/Button';
import FormField from '@/Components/UI/FormField';
import Input from '@/Components/UI/Input';
import Select from '@/Components/UI/Select';
import Textarea from '@/Components/UI/Textarea';
import { Head, useForm } from '@inertiajs/react';

function DynamicField({ field, value, onChange, error }) {
    if (field.field_type === 'textarea') return <Textarea value={value || ''} onChange={(e) => onChange(e.target.value)} error={!!error} />;
    if (field.field_type === 'boolean') return <Select value={value ?? ''} onChange={(e) => onChange(e.target.value === '' ? null : e.target.value === 'true')}><option value="">Not set</option><option value="true">Yes</option><option value="false">No</option></Select>;
    if (field.field_type === 'single_select') return <Select value={value || ''} onChange={(e) => onChange(e.target.value)}><option value="">Select…</option>{(field.options || []).map((x) => <option key={x}>{x}</option>)}</Select>;
    return <Input type={['date', 'datetime'].includes(field.field_type) ? (field.field_type === 'date' ? 'date' : 'datetime-local') : ['integer', 'decimal', 'currency'].includes(field.field_type) ? 'number' : field.field_type === 'email' ? 'email' : field.field_type === 'url' ? 'url' : 'text'} value={value || ''} onChange={(e) => onChange(e.target.value)} error={!!error} placeholder={field.placeholder || ''} />;
}

export default function Form({ contact, companies, owners, tags, customFields, customValues }) {
    const editing = !!contact;
    const { data, setData, post, put, processing, errors } = useForm({ first_name: contact?.first_name || '', last_name: contact?.last_name || '', display_name: contact?.display_name || '', email: contact?.email || '', secondary_email: contact?.secondary_email || '', phone: contact?.phone || '', secondary_phone: contact?.secondary_phone || '', country: contact?.country || '', timezone: contact?.timezone || '', preferred_language: contact?.preferred_language || '', status: contact?.status || 'active', source: contact?.source || 'manual', owner_id: contact?.owner_id || '', company_id: contact?.company_id || '', external_id: contact?.external_id || '', tag_ids: contact?.tags?.map((x) => x.id) || [], contact_points: contact?.contact_points || [], custom_fields: customValues || {} });
    const submit = (e) => { e.preventDefault(); editing ? put(route('tenant.admin.customers.contacts.update', contact.public_uuid)) : post(route('tenant.admin.customers.contacts.store')); };
    return <CustomersShell title={editing ? `Edit ${contact.display_name}` : 'Add contact'} description="Maintain clean customer identity and routing data."><Head title={editing ? 'Edit contact' : 'Add contact'} /><form onSubmit={submit} className="space-y-5"><div className="grid gap-5 rounded-lg border border-slate-200 bg-white p-5 shadow-soft md:grid-cols-2">
        <FormField label="First name" error={errors.first_name}><Input value={data.first_name} onChange={(e) => setData('first_name', e.target.value)} error={!!errors.first_name} /></FormField><FormField label="Last name" error={errors.last_name}><Input value={data.last_name} onChange={(e) => setData('last_name', e.target.value)} /></FormField>
        <FormField label="Display name" error={errors.display_name} hint="Generated from the name when left blank."><Input value={data.display_name} onChange={(e) => setData('display_name', e.target.value)} /></FormField><FormField label="Status" error={errors.status}><Select value={data.status} onChange={(e) => setData('status', e.target.value)}><option value="active">Active</option><option value="vip">VIP</option><option value="inactive">Inactive</option><option value="blocked">Blocked</option></Select></FormField>
        <FormField label="Primary email" error={errors.email}><Input type="email" value={data.email} onChange={(e) => setData('email', e.target.value)} /></FormField><FormField label="Secondary email" error={errors.secondary_email}><Input type="email" value={data.secondary_email} onChange={(e) => setData('secondary_email', e.target.value)} /></FormField>
        <FormField label="Primary phone" error={errors.phone}><Input value={data.phone} onChange={(e) => setData('phone', e.target.value)} /></FormField><FormField label="Secondary phone" error={errors.secondary_phone}><Input value={data.secondary_phone} onChange={(e) => setData('secondary_phone', e.target.value)} /></FormField>
        <FormField label="Company"><Select value={data.company_id} onChange={(e) => setData('company_id', e.target.value)}><option value="">No company</option>{companies.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormField><FormField label="Owner"><Select value={data.owner_id} onChange={(e) => setData('owner_id', e.target.value)}><option value="">Unassigned</option>{owners.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormField>
        <FormField label="Country code" hint="ISO 2-letter code"><Input maxLength={2} value={data.country} onChange={(e) => setData('country', e.target.value.toUpperCase())} /></FormField><FormField label="Timezone"><Input value={data.timezone} onChange={(e) => setData('timezone', e.target.value)} placeholder="Asia/Kathmandu" /></FormField>
        <FormField label="Preferred language"><Input value={data.preferred_language} onChange={(e) => setData('preferred_language', e.target.value)} placeholder="en" /></FormField><FormField label="External ID"><Input value={data.external_id} onChange={(e) => setData('external_id', e.target.value)} /></FormField>
        <FormField label="Tags" className="md:col-span-2"><div className="flex flex-wrap gap-2">{tags.map((tag) => <label key={tag.id} className="flex items-center gap-2 rounded-md border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" checked={data.tag_ids.includes(tag.id)} onChange={(e) => setData('tag_ids', e.target.checked ? [...data.tag_ids, tag.id] : data.tag_ids.filter((id) => id !== tag.id))} />{tag.name}</label>)}</div></FormField>
    </div>{customFields.length > 0 && <div className="grid gap-5 rounded-lg border border-slate-200 bg-white p-5 shadow-soft md:grid-cols-2"><h2 className="md:col-span-2 text-sm font-semibold text-slate-900">Custom fields</h2>{customFields.map((field) => <FormField key={field.public_uuid} label={field.label} error={errors[`custom_fields.${field.key}`]} hint={field.help_text}><DynamicField field={field} value={data.custom_fields[field.key]} onChange={(value) => setData('custom_fields', { ...data.custom_fields, [field.key]: value })} error={errors[`custom_fields.${field.key}`]} /></FormField>)}</div>}<div className="flex justify-end gap-2"><Button href={route('tenant.admin.customers.contacts.index')} variant="secondary">Cancel</Button><Button type="submit" variant="brand" loading={processing}>{editing ? 'Save changes' : 'Create contact'}</Button></div></form></CustomersShell>;
}
