import CustomersShell from '@/Components/Tenant/Customers/CustomersShell';
import Avatar from '@/Components/UI/Avatar';
import Badge from '@/Components/UI/Badge';
import Button from '@/Components/UI/Button';
import { Card, SectionCard } from '@/Components/UI/Card';
import { Head, router, usePage } from '@inertiajs/react';
import { Archive, Building2, Mail, Pencil, Phone, Sparkles, UserRound } from 'lucide-react';

const tones = { active: 'brand', vip: 'warning', blocked: 'danger', inactive: 'neutral' };

export default function Show({ contact, aiBrief, aiEnabled }) {
    const permissions = usePage().props.auth?.permissions || [];
    const archive = () => window.confirm(`Archive ${contact.display_name}? Their history will be retained and the contact can be restored.`) && router.delete(route('tenant.admin.customers.contacts.destroy', contact.public_uuid));
    return <CustomersShell title={contact.display_name} description="Customer profile and chronological support activity." actions={<>{aiEnabled && <Button variant="secondary" icon={Sparkles} onClick={() => router.post(route('tenant.admin.customers.contacts.ai-brief', contact.public_uuid), {}, { preserveScroll: true })}>Generate brief</Button>}{permissions.includes('customers.update') && <Button href={route('tenant.admin.customers.contacts.edit', contact.public_uuid)} variant="secondary" icon={Pencil}>Edit</Button>}{permissions.includes('customers.delete') && <Button variant="danger" icon={Archive} onClick={archive}>Archive</Button>}</>}>
        <Head title={contact.display_name} /><div className="grid gap-5 xl:grid-cols-[340px,1fr]"><div className="space-y-5"><Card><div className="flex items-center gap-3"><Avatar name={contact.display_name} size="lg" /><div><h2 className="font-semibold text-slate-900">{contact.display_name}</h2><Badge tone={tones[contact.status]} className="mt-1">{contact.status}</Badge></div></div><dl className="mt-5 space-y-3 text-sm">{contact.email && <div className="flex gap-2"><Mail className="h-4 w-4 text-slate-400" /><span>{contact.email}</span></div>}{contact.phone && <div className="flex gap-2"><Phone className="h-4 w-4 text-slate-400" /><span>{contact.phone}</span></div>}{contact.company && <div className="flex gap-2"><Building2 className="h-4 w-4 text-slate-400" /><span>{contact.company.name}</span></div>}<div className="flex gap-2"><UserRound className="h-4 w-4 text-slate-400" /><span>{contact.owner?.name || 'Unassigned'}</span></div></dl>{contact.tags.length > 0 && <div className="mt-5 flex flex-wrap gap-1">{contact.tags.map((tag) => <Badge key={tag.public_uuid}>{tag.name}</Badge>)}</div>}</Card>
            {aiBrief && <SectionCard title="AI support brief"><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{aiBrief.text}</p></SectionCard>}{(contact.contact_points.length > 0 || contact.custom_field_values.length > 0) && <SectionCard title="Additional details"><dl className="space-y-3 text-sm">{contact.contact_points.map((point) => <div key={point.id}><dt className="text-xs font-medium uppercase text-slate-400">{point.label || point.type}</dt><dd className="text-slate-700">{point.value}</dd></div>)}{contact.custom_field_values.map((value) => <div key={value.id}><dt className="text-xs font-medium uppercase text-slate-400">{value.field.label}</dt><dd className="text-slate-700">{Array.isArray(value.value) ? value.value.join(', ') : String(value.value ?? '—')}</dd></div>)}</dl></SectionCard>}</div>
            <SectionCard title="Activity timeline" description="Append-only history across customer support resources.">{contact.activities.length ? <ol className="relative space-y-6 border-l border-slate-200 pl-6">{contact.activities.map((activity) => <li key={activity.public_uuid}><span className="absolute -left-1.5 mt-1.5 h-3 w-3 rounded-full border-2 border-white bg-brand-500" /><p className="text-sm font-medium text-slate-800">{activity.description}</p><p className="mt-1 text-xs text-slate-500">{activity.actor?.name || activity.actor_name || 'System'} · {new Date(activity.occurred_at).toLocaleString()}</p></li>)}</ol> : <p className="text-sm text-slate-500">No activity has been recorded yet.</p>}</SectionCard></div>
    </CustomersShell>;
}
