import PageHeader from '@/Components/Superadmin/PageHeader';
import StatusBadge from '@/Components/Superadmin/StatusBadge';
import { SectionCard } from '@/Components/UI/Card';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';

const tabs = [['admins','Platform admins','superadmin.security.admins.index'],['roles','Roles & permissions','superadmin.security.roles.index'],['audit','Audit logs','superadmin.security.audit.index'],['logins','Login activity','superadmin.security.logins.index']];

function Admins({ admins, roles }) { const form=useForm({name:'',email:'',role_id:roles?.[0]?.id||''});const action=(admin,payload)=>router.post(route('superadmin.security.admins.access',admin.public_uuid),payload,{preserveScroll:true});return <SectionCard title="Platform administrators" actions={<form onSubmit={e=>{e.preventDefault();form.post(route('superadmin.security.admins.store'),{onSuccess:()=>form.reset('name','email')})}} className="flex flex-wrap gap-2"><input required placeholder="Name" className="rounded-lg border-slate-300 text-sm" value={form.data.name} onChange={e=>form.setData('name',e.target.value)}/><input required type="email" placeholder="Email" className="rounded-lg border-slate-300 text-sm" value={form.data.email} onChange={e=>form.setData('email',e.target.value)}/><select className="rounded-lg border-slate-300 text-sm" value={form.data.role_id} onChange={e=>form.setData('role_id',e.target.value)}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Invite</button></form>}><div className="divide-y">{admins.data.map(admin=><div key={admin.id} className="space-y-3 py-4"><div className="grid gap-3 sm:grid-cols-[1fr_200px_110px]"><div><p className="font-semibold">{admin.name}</p><p className="text-sm text-slate-500">{admin.email}</p></div><select value={admin.roles[0]?.id||''} onChange={e=>action(admin,{action:'assign_role',role_id:e.target.value})} className="rounded-lg border-slate-300 text-sm">{roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select><StatusBadge status={admin.is_active?'active':'suspended'}/></div><div className="flex flex-wrap gap-4 text-sm"><button onClick={()=>{const reason=window.prompt('Reason for this status change');if(reason)router.put(route('superadmin.security.admins.status',admin.public_uuid),{is_active:!admin.is_active,reason})}} className="font-semibold text-indigo-600">{admin.is_active?'Suspend':'Activate'}</button><button onClick={()=>action(admin,{action:'reset_access'})} className="font-semibold text-indigo-600">Reset access</button><button onClick={()=>action(admin,{action:'require_2fa',required:!admin.two_factor_required})} className="font-semibold text-indigo-600">{admin.two_factor_required?'Remove 2FA requirement':'Require 2FA'}</button><button onClick={()=>action(admin,{action:'revoke_sessions'})} className="font-semibold text-rose-600">Revoke sessions</button></div></div>)}</div></SectionCard> }

function Roles({roles,permissions}) { return <div className="space-y-5">{roles.map(role=><RoleEditor key={role.id} role={role} permissions={permissions}/>)}</div> }
function RoleEditor({role,permissions}) { const form=useForm({permissions:role.permissions.map(p=>p.name)});const toggle=(name)=>form.setData('permissions',form.data.permissions.includes(name)?form.data.permissions.filter(v=>v!==name):[...form.data.permissions,name]);return <SectionCard title={role.name} description={`${form.data.permissions.length} permissions`}><form onSubmit={e=>{e.preventDefault();form.put(route('superadmin.security.roles.update',role.id))}}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{permissions.map(permission=><label key={permission.id} className="flex items-center gap-2 rounded bg-slate-50 px-3 py-2 text-sm"><input type="checkbox" className="rounded" checked={form.data.permissions.includes(permission.name)} onChange={()=>toggle(permission.name)}/>{permission.name}</label>)}</div><button className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Save permissions</button></form></SectionCard> }

function Audit({logs}) { return <SectionCard title="Audit log"><div className="divide-y">{logs.data.map(log=><div key={log.id} className="grid gap-2 py-4 text-sm sm:grid-cols-[180px_180px_1fr]"><span>{new Date(log.created_at).toLocaleString()}</span><span>{log.administrator?.name||'System'}</span><div><p className="font-semibold">{log.action}</p><p className="text-xs text-slate-500">{log.entity_type} {log.entity_id} · {log.ip_address}</p></div></div>)}</div></SectionCard> }
function Logins({attempts}) { return <SectionCard title="Administrator login activity"><div className="divide-y">{attempts.data.map(item=><div key={item.id} className="grid gap-2 py-4 text-sm sm:grid-cols-[180px_1fr_120px_160px]"><span>{new Date(item.created_at).toLocaleString()}</span><span>{item.email}</span><StatusBadge status={item.successful?'success':'failed'}/><span className="text-slate-500">{item.ip_address}</span></div>)}</div></SectionCard> }

export default function Index({tab,admins,roles=[],permissions=[],auditLogs,loginAttempts}){return <AuthenticatedLayout header={<PageHeader title="Platform security" subtitle="Administrators, granular roles, immutable audit history, and login activity."/>}><Head title="Security"/><div className="mb-5 flex flex-wrap gap-2">{tabs.map(([value,label,routeName])=><Link key={value} href={route(routeName)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${tab===value?'bg-slate-900 text-white':'border bg-white text-slate-600'}`}>{label}</Link>)}</div>{tab==='admins'&&<Admins admins={admins} roles={roles}/>} {tab==='roles'&&<Roles roles={roles} permissions={permissions}/>} {tab==='audit'&&<Audit logs={auditLogs}/>} {tab==='logins'&&<Logins attempts={loginAttempts}/>}</AuthenticatedLayout>}
